# -*- coding: utf-8 -*-
"""Append UoE exercises to reach 20 per lesson (5 per type) for A1, A2, B1, B2(11-20)."""
import json
from pathlib import Path

# Each list APPENDS to existing exercises; final goal = 20 per lesson with ~5 of each type.
ADD = {
"A1": {
 1: [  # BE + a/an
  {"type":"mc_cloze","sentence":"She ___ a developer.","options":["am","is","are","be"],"a":1,"explain":"3rd sing."},
  {"type":"mc_cloze","sentence":"We ___ on the IT team.","options":["am","is","are","be"],"a":2,"explain":"plural"},
  {"type":"mc_cloze","sentence":"They ___ in the data centre.","options":["am","is","are","being"],"a":2,"explain":"plural"},
  {"type":"mc_cloze","sentence":"You ___ my new colleague.","options":["am","is","are","be"],"a":2,"explain":"YOU + are"},
  {"type":"cloze","sentence":"He is ___ analyst.","a":"an","alts":["an"],"explain":"vowel sound"},
  {"type":"cloze","sentence":"It is ___ small office.","a":"a","alts":["a"],"explain":"consonant"},
  {"type":"cloze","sentence":"We are ___ engineers.","a":"","alts":["",None],"explain":"no article + plural"},
  {"type":"cloze","sentence":"Maria is ___ Lima.","a":"from","alts":["from"],"explain":"origin"},
  {"type":"word_form","base":"DEVELOP","sentence":"She is a software ___ .","a":"developer","alts":["developer"],"explain":"-er"},
  {"type":"word_form","base":"ANALYSE","sentence":"He is an ___ .","a":"analyst","alts":["analyst"],"explain":"-st"},
  {"type":"word_form","base":"MANAGE","sentence":"My ___ is Ana.","a":"manager","alts":["manager"],"explain":"-er"},
  {"type":"word_form","base":"TEACH","sentence":"She is a ___ at the university.","a":"teacher","alts":["teacher"],"explain":"-er"},
  {"type":"key_word","original":"He's a doctor.","key":"IS","gap_template":"He ___ doctor.","a":"is a","alts":["is a"],"explain":"contraction → full"},
  {"type":"key_word","original":"They're engineers.","key":"ARE","gap_template":"They ___ engineers.","a":"are","alts":["are"],"explain":"plural"},
  {"type":"key_word","original":"I am Ana.","key":"NAME","gap_template":"My ___ Ana.","a":"name is","alts":["name is"],"explain":"name + is"},
  {"type":"key_word","original":"She works at IBM.","key":"AT","gap_template":"She is ___ IBM.","a":"at","alts":["at"],"explain":"location"},
  {"type":"key_word","original":"He's twenty-four.","key":"OLD","gap_template":"He is twenty-four years ___ .","a":"old","alts":["old"],"explain":"age"}],
 2: [  # Alphabet, URLs, emails
  {"type":"mc_cloze","sentence":"D in NATO is ___ .","options":["Dog","Delta","David","Dave"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"M in NATO is ___ .","options":["Mary","Mike","Max","Music"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"In a URL, '/' is ___ .","options":["dot","slash","at","dash"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"In an email, '@' is ___ .","options":["dot","slash","at","hash"],"a":2,"explain":""},
  {"type":"cloze","sentence":"My email is paolo ___ gmail.","a":"at","alts":["at","@"],"explain":"@ = at"},
  {"type":"cloze","sentence":"The URL has 'www ___ google' .","a":"dot","alts":["dot","."],"explain":"."},
  {"type":"cloze","sentence":"In passwords write a ___ , not a zero.","a":"O","alts":["O","letter O"],"explain":"O vs 0"},
  {"type":"cloze","sentence":"Spell it ___ Bravo Alpha Delta.","a":"as","alts":["as"],"explain":"as"},
  {"type":"word_form","base":"SPELL","sentence":"Can you ___ that, please?","a":"spell","alts":["spell"],"explain":"verb"},
  {"type":"word_form","base":"PRONOUNCE","sentence":"___ this URL clearly.","a":"Pronounce","alts":["Pronounce"],"explain":"verb"},
  {"type":"word_form","base":"CAPITAL","sentence":"Use a ___ letter at the start.","a":"capital","alts":["capital"],"explain":"adj"},
  {"type":"word_form","base":"LOWER","sentence":"URLs are usually in ___ case.","a":"lower","alts":["lower"],"explain":"adj"},
  {"type":"key_word","original":"What is your email?","key":"IS","gap_template":"What ___ email?","a":"is your","alts":["is your"],"explain":""},
  {"type":"key_word","original":"Spell your name slowly.","key":"PLEASE","gap_template":"Spell your name slowly, ___ .","a":"please","alts":["please"],"explain":"polite"},
  {"type":"key_word","original":"B is Bravo.","key":"FOR","gap_template":"B ___ Bravo.","a":"for","alts":["for","stands for"],"explain":""},
  {"type":"key_word","original":"That is John dot smith at gmail.","key":"AT","gap_template":"That is John dot smith ___ gmail.","a":"at","alts":["at"],"explain":""},
  {"type":"key_word","original":"Could you say it again?","key":"REPEAT","gap_template":"Could you ___ it?","a":"repeat","alts":["repeat"],"explain":""}],
 3: [  # Numbers, versions, dates
  {"type":"mc_cloze","sentence":"Patch Tuesday is the ___ Tuesday of the month.","options":["first","second","third","fourth"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"The MAJOR number is the ___ one in 1.2.3.","options":["first","second","third","fourth"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"In '12.4.5', the patch number is ___ .","options":["12","4","5","6"],"a":2,"explain":""},
  {"type":"mc_cloze","sentence":"v3.0.0 is a ___ change.","options":["small","big","minor","patch"],"a":1,"explain":""},
  {"type":"cloze","sentence":"Today is the ___ of April.","a":"twenty-third","alts":["twenty-third","23rd"],"explain":""},
  {"type":"cloze","sentence":"Patch ___ is on the second Tuesday.","a":"Tuesday","alts":["Tuesday"],"explain":""},
  {"type":"cloze","sentence":"Python 3 ___ 12 ___ 4 (read aloud).","a":"point","alts":["point"],"explain":""},
  {"type":"cloze","sentence":"The release is ___ May.","a":"in","alts":["in"],"explain":"month"},
  {"type":"word_form","base":"VERSION","sentence":"What ___ are you on?","a":"version","alts":["version"],"explain":""},
  {"type":"word_form","base":"UPDATE","sentence":"There is a new ___ .","a":"update","alts":["update"],"explain":""},
  {"type":"word_form","base":"INSTALL","sentence":"Please ___ the patch.","a":"install","alts":["install"],"explain":"verb"},
  {"type":"word_form","base":"RELEASE","sentence":"The ___ date is May 5.","a":"release","alts":["release"],"explain":"noun"},
  {"type":"key_word","original":"Update the system today.","key":"NEED","gap_template":"You ___ update the system today.","a":"need to","alts":["need to"],"explain":""},
  {"type":"key_word","original":"It is on May 12.","key":"ON","gap_template":"It is ___ May 12.","a":"on","alts":["on"],"explain":"date"},
  {"type":"key_word","original":"The version is 14.","key":"FOURTEEN","gap_template":"The version is ___ .","a":"fourteen","alts":["fourteen"],"explain":""},
  {"type":"key_word","original":"It is the second update.","key":"ORDINAL","gap_template":"It is the ___ update.","a":"second","alts":["second","2nd"],"explain":""},
  {"type":"key_word","original":"The release is in 2026.","key":"IN","gap_template":"The release is ___ 2026.","a":"in","alts":["in"],"explain":"year"}],
 4: [  # Hardware (there is/are)
  {"type":"mc_cloze","sentence":"___ a CPU inside the computer.","options":["There is","There are","It is","They are"],"a":0,"explain":"sing."},
  {"type":"mc_cloze","sentence":"___ four USB ports.","options":["There is","There are","It is","They"],"a":1,"explain":"pl."},
  {"type":"mc_cloze","sentence":"The CPU is the ___ of the computer.","options":["leg","brain","arm","ear"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"The keyboard is ___ typing.","options":["of","at","for","on"],"a":2,"explain":"FOR + purpose"},
  {"type":"cloze","sentence":"There ___ many cables behind the tower.","a":"are","alts":["are"],"explain":"pl."},
  {"type":"cloze","sentence":"There ___ a fan inside the laptop.","a":"is","alts":["is"],"explain":"sing."},
  {"type":"cloze","sentence":"Servers live ___ data centres.","a":"in","alts":["in"],"explain":"location"},
  {"type":"cloze","sentence":"Keep the laptop ___ the desk.","a":"on","alts":["on"],"explain":"surface"},
  {"type":"word_form","base":"PROCESS","sentence":"The CPU is the ___ .","a":"processor","alts":["processor"],"explain":"-or"},
  {"type":"word_form","base":"MEMORY","sentence":"More ___ makes the laptop faster.","a":"memory","alts":["memory"],"explain":"noun"},
  {"type":"word_form","base":"PERIPHERAL","sentence":"Keyboard and mouse are ___ .","a":"peripherals","alts":["peripherals"],"explain":"plural"},
  {"type":"word_form","base":"STORE","sentence":"The SSD is for ___ .","a":"storage","alts":["storage"],"explain":"-age"},
  {"type":"key_word","original":"My laptop has 8 GB of RAM.","key":"HAS","gap_template":"My laptop ___ 8 GB of RAM.","a":"has","alts":["has"],"explain":""},
  {"type":"key_word","original":"There is a webcam.","key":"GOT","gap_template":"It has ___ webcam.","a":"got a","alts":["got a"],"explain":""},
  {"type":"key_word","original":"Two USB ports exist on the side.","key":"ARE","gap_template":"There ___ on the side.","a":"are two USB ports","alts":["are two USB ports"],"explain":""},
  {"type":"key_word","original":"It is a laptop.","key":"PORTABLE","gap_template":"It is a ___ computer.","a":"portable","alts":["portable"],"explain":""},
  {"type":"key_word","original":"The mouse is on the desk.","key":"WHERE","gap_template":"___ the mouse?","a":"Where is","alts":["Where is"],"explain":""}],
 5: [  # Software basics (imperatives + can)
  {"type":"mc_cloze","sentence":"___ Next to continue.","options":["Click","Clicks","Clicking","To click"],"a":0,"explain":"imperative"},
  {"type":"mc_cloze","sentence":"___ click on strange links.","options":["No","Not","Don't","Doesn't"],"a":2,"explain":"neg imp"},
  {"type":"mc_cloze","sentence":"Linux ___ free.","options":["am","is","are","be"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"You ___ download from the official site.","options":["should","must to","ought","need"],"a":0,"explain":"advice"},
  {"type":"cloze","sentence":"Always download ___ the official website.","a":"from","alts":["from"],"explain":"source"},
  {"type":"cloze","sentence":"___ click 'Finish' at the end.","a":"Then","alts":["Then","Finally"],"explain":"sequence"},
  {"type":"cloze","sentence":"Verify ___ hash before installing.","a":"the","alts":["the"],"explain":"def. art."},
  {"type":"cloze","sentence":"You ___ install free programs.","a":"can","alts":["can"],"explain":"possibility"},
  {"type":"word_form","base":"INSTALL","sentence":"Run the ___ as admin.","a":"installer","alts":["installer"],"explain":"-er"},
  {"type":"word_form","base":"DOWNLOAD","sentence":"___ the file from the site.","a":"Download","alts":["Download"],"explain":"verb"},
  {"type":"word_form","base":"VERIFY","sentence":"___ the hash matches.","a":"Verify","alts":["Verify"],"explain":"verb"},
  {"type":"word_form","base":"WIZARD","sentence":"Follow the install ___ .","a":"wizard","alts":["wizard"],"explain":"noun"},
  {"type":"key_word","original":"Do not download cracked software.","key":"DON'T","gap_template":"___ download cracked software.","a":"Don't","alts":["Don't"],"explain":""},
  {"type":"key_word","original":"It is possible to install it now.","key":"CAN","gap_template":"You ___ install it now.","a":"can","alts":["can"],"explain":""},
  {"type":"key_word","original":"You should not skip the EULA.","key":"DON'T","gap_template":"___ skip the EULA.","a":"Don't","alts":["Don't"],"explain":""},
  {"type":"key_word","original":"Always read the prompts.","key":"READ","gap_template":"Always ___ the prompts.","a":"read","alts":["read"],"explain":""},
  {"type":"key_word","original":"You can use Linux for free.","key":"FREE","gap_template":"Linux is ___ .","a":"free","alts":["free"],"explain":""}],
 6: [  # Workspace (prepositions of place)
  {"type":"mc_cloze","sentence":"My laptop is ___ the desk.","options":["in","on","under","at"],"a":1,"explain":"surface"},
  {"type":"mc_cloze","sentence":"The cables are ___ the desk.","options":["on","at","under","next"],"a":2,"explain":"below"},
  {"type":"mc_cloze","sentence":"My monitor is ___ to the lamp.","options":["next","on","under","behind"],"a":0,"explain":"beside"},
  {"type":"mc_cloze","sentence":"The chair is ___ of the desk.","options":["in front","front","behind of","at"],"a":0,"explain":"facing"},
  {"type":"cloze","sentence":"My pen is ___ the drawer.","a":"in","alts":["in"],"explain":"inside"},
  {"type":"cloze","sentence":"The server is ___ the rack.","a":"in","alts":["in"],"explain":"inside"},
  {"type":"cloze","sentence":"The keyboard is ___ front of me.","a":"in","alts":["in"],"explain":"in front of"},
  {"type":"cloze","sentence":"Her monitor is ___ the right.","a":"on","alts":["on"],"explain":"side"},
  {"type":"word_form","base":"WORK","sentence":"This is my ___ .","a":"workspace","alts":["workspace"],"explain":"compound"},
  {"type":"word_form","base":"OFFICE","sentence":"Our ___ is in San Isidro.","a":"office","alts":["office"],"explain":"unchanged"},
  {"type":"word_form","base":"CLEAN","sentence":"A ___ desk is good practice.","a":"clean","alts":["clean"],"explain":"adj"},
  {"type":"word_form","base":"ORGANISE","sentence":"My desk is ___ .","a":"organised","alts":["organised","organized"],"explain":"-ed"},
  {"type":"key_word","original":"My laptop is on the desk.","key":"DESK","gap_template":"There is a laptop on the ___ .","a":"desk","alts":["desk"],"explain":""},
  {"type":"key_word","original":"Where are the cables?","key":"UNDER","gap_template":"The cables are ___ desk.","a":"under the","alts":["under the"],"explain":""},
  {"type":"key_word","original":"Her chair is opposite the desk.","key":"FRONT","gap_template":"Her chair is in ___ desk.","a":"front of the","alts":["front of the"],"explain":""},
  {"type":"key_word","original":"The lamp is beside the monitor.","key":"NEXT","gap_template":"The lamp is ___ monitor.","a":"next to the","alts":["next to the"],"explain":""},
  {"type":"key_word","original":"There are books on the shelf.","key":"SHELF","gap_template":"There are books on the ___ .","a":"shelf","alts":["shelf"],"explain":""}],
 7: [  # Routines (present simple + freq)
  {"type":"mc_cloze","sentence":"I ___ check my email at 9.","options":["always","am always","be always","always am"],"a":0,"explain":"before main verb"},
  {"type":"mc_cloze","sentence":"She ___ late to meetings.","options":["usually is","is usually","usually","be usually"],"a":1,"explain":"after BE"},
  {"type":"mc_cloze","sentence":"We ___ have lunch at 1.","options":["never","are never","never are","not"],"a":0,"explain":"before main verb"},
  {"type":"mc_cloze","sentence":"He ___ tickets every day.","options":["read","reads","reading","is read"],"a":1,"explain":"3rd sing."},
  {"type":"cloze","sentence":"Pedro ___ at 8.30 every day.","a":"arrives","alts":["arrives"],"explain":"3rd sing."},
  {"type":"cloze","sentence":"The team has a meeting ___ 9.","a":"at","alts":["at"],"explain":"clock"},
  {"type":"cloze","sentence":"On Fridays we ___ the retro.","a":"have","alts":["have"],"explain":"plural"},
  {"type":"cloze","sentence":"He ___ helps new employees.","a":"sometimes","alts":["sometimes"],"explain":"adverb"},
  {"type":"word_form","base":"HELP","sentence":"He is a great ___ .","a":"helper","alts":["helper"],"explain":"-er"},
  {"type":"word_form","base":"ROUTINE","sentence":"My daily ___ starts at 8.","a":"routine","alts":["routine"],"explain":"noun"},
  {"type":"word_form","base":"MORNING","sentence":"In the ___ I read tickets.","a":"morning","alts":["morning"],"explain":""},
  {"type":"word_form","base":"AFTERNOON","sentence":"In the ___ I write reports.","a":"afternoon","alts":["afternoon"],"explain":""},
  {"type":"key_word","original":"He works at the helpdesk.","key":"WORKS","gap_template":"He ___ helpdesk.","a":"works at the","alts":["works at the"],"explain":""},
  {"type":"key_word","original":"The meeting starts at 9.","key":"STARTS","gap_template":"The meeting ___ 9.","a":"starts at","alts":["starts at"],"explain":""},
  {"type":"key_word","original":"I never miss the standup.","key":"NEVER","gap_template":"I ___ miss the standup.","a":"never","alts":["never"],"explain":""},
  {"type":"key_word","original":"She is usually busy.","key":"USUALLY","gap_template":"She ___ busy.","a":"is usually","alts":["is usually"],"explain":""},
  {"type":"key_word","original":"They have lunch at 1.","key":"LUNCH","gap_template":"They have ___ 1.","a":"lunch at","alts":["lunch at"],"explain":""}],
 8: [  # Files (have got + some/any)
  {"type":"mc_cloze","sentence":"I ___ got three folders.","options":["have","has","am","is"],"a":0,"explain":"1st sing."},
  {"type":"mc_cloze","sentence":"She ___ got the file.","options":["have","has","is","are"],"a":1,"explain":"3rd sing."},
  {"type":"mc_cloze","sentence":"We have ___ documents to review.","options":["any","some","much","a"],"a":1,"explain":"affirm."},
  {"type":"mc_cloze","sentence":"Have you got ___ free space?","options":["some","any","a","much"],"a":1,"explain":"question"},
  {"type":"cloze","sentence":"Let me know if you have ___ questions.","a":"any","alts":["any"],"explain":"if-clause"},
  {"type":"cloze","sentence":"There are ___ ZIP files in the folder.","a":"some","alts":["some"],"explain":"affirm."},
  {"type":"cloze","sentence":"I haven't got ___ files on my desktop.","a":"any","alts":["any"],"explain":"neg."},
  {"type":"cloze","sentence":"Save the file ___ PDF.","a":"as","alts":["as"],"explain":"format"},
  {"type":"word_form","base":"BACK","sentence":"Make a ___ before deleting.","a":"backup","alts":["backup","back-up"],"explain":"compound"},
  {"type":"word_form","base":"SHARE","sentence":"This is the ___ folder.","a":"shared","alts":["shared"],"explain":"-ed adj"},
  {"type":"word_form","base":"DOCUMENT","sentence":"Open the Word ___ .","a":"document","alts":["document"],"explain":"noun"},
  {"type":"word_form","base":"NAME","sentence":"What is the ___ of the file?","a":"name","alts":["name"],"explain":"noun"},
  {"type":"key_word","original":"I have three folders.","key":"GOT","gap_template":"I have ___ three folders.","a":"got","alts":["got"],"explain":""},
  {"type":"key_word","original":"She has the latest version.","key":"GOT","gap_template":"She has ___ version.","a":"got the latest","alts":["got the latest"],"explain":""},
  {"type":"key_word","original":"My desktop is empty.","key":"ANY","gap_template":"I haven't got ___ desktop.","a":"any files on my","alts":["any files on my"],"explain":""},
  {"type":"key_word","original":"Send the file please.","key":"COULD","gap_template":"___ send the file?","a":"Could you","alts":["Could you"],"explain":""},
  {"type":"key_word","original":"It is in the shared folder.","key":"FOLDER","gap_template":"It is in the shared ___ .","a":"folder","alts":["folder"],"explain":""}],
 9: [  # Internet (present continuous)
  {"type":"mc_cloze","sentence":"The router ___ rebooting now.","options":["am","is","are","be"],"a":1,"explain":"3rd sing."},
  {"type":"mc_cloze","sentence":"I ___ a video call right now.","options":["join","joining","am joining","joins"],"a":2,"explain":"BE + ing"},
  {"type":"mc_cloze","sentence":"They ___ streaming the conference.","options":["is","are","am","be"],"a":1,"explain":"plural"},
  {"type":"mc_cloze","sentence":"Look! The page ___ slowly.","options":["load","loads","is loading","loaded"],"a":2,"explain":"now"},
  {"type":"cloze","sentence":"My phone is ___ to the Wi-Fi.","a":"connecting","alts":["connecting"],"explain":"-ing"},
  {"type":"cloze","sentence":"The system ___ updating right now.","a":"is","alts":["is"],"explain":"BE"},
  {"type":"cloze","sentence":"They are not ___ the call.","a":"joining","alts":["joining"],"explain":"-ing"},
  {"type":"cloze","sentence":"___ you using a VPN?","a":"Are","alts":["Are"],"explain":"question"},
  {"type":"word_form","base":"CONNECT","sentence":"The Wi-Fi ___ is slow.","a":"connection","alts":["connection"],"explain":"-tion"},
  {"type":"word_form","base":"DOWNLOAD","sentence":"I am ___ a big file.","a":"downloading","alts":["downloading"],"explain":"-ing"},
  {"type":"word_form","base":"UPLOAD","sentence":"___ the report now.","a":"Uploading","alts":["Uploading","Upload"],"explain":""},
  {"type":"word_form","base":"RESTART","sentence":"___ your computer.","a":"Restart","alts":["Restart"],"explain":"verb"},
  {"type":"key_word","original":"My Wi-Fi is slow today.","key":"SLOW","gap_template":"My Wi-Fi is ___ today.","a":"slow","alts":["slow"],"explain":""},
  {"type":"key_word","original":"I'm on a video call.","key":"AM","gap_template":"I ___ a video call.","a":"am on","alts":["am on"],"explain":""},
  {"type":"key_word","original":"Try again, please.","key":"TRY","gap_template":"___ again, please.","a":"Try","alts":["Try"],"explain":"imp."},
  {"type":"key_word","original":"The page does not load.","key":"NOT","gap_template":"The page is ___ loading.","a":"not","alts":["not"],"explain":""},
  {"type":"key_word","original":"They are watching.","key":"WATCHING","gap_template":"They are ___ video.","a":"watching the","alts":["watching the"],"explain":""}],
 10: [  # Passwords (imperatives + should)
  {"type":"mc_cloze","sentence":"You ___ enable 2FA.","options":["should","must to","ought","need"],"a":0,"explain":"advice"},
  {"type":"mc_cloze","sentence":"___ share your password.","options":["No","Not","Don't","Doesn't"],"a":2,"explain":"neg imp"},
  {"type":"mc_cloze","sentence":"A passphrase has ___ random words.","options":["four","fours","forth","fourth"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"You ___ reuse passwords.","options":["should","shouldn't","must to","not"],"a":1,"explain":"neg advice"},
  {"type":"cloze","sentence":"Use a strong ___ , not '123456'.","a":"password","alts":["password","passphrase"],"explain":""},
  {"type":"cloze","sentence":"Always ___ your password.","a":"change","alts":["change"],"explain":""},
  {"type":"cloze","sentence":"Two-factor stops most ___ .","a":"attacks","alts":["attacks"],"explain":"plural"},
  {"type":"cloze","sentence":"Never share ___ password.","a":"your","alts":["your"],"explain":"poss."},
  {"type":"word_form","base":"SECURE","sentence":"Strong ___ matters.","a":"security","alts":["security"],"explain":"-ity"},
  {"type":"word_form","base":"AUTHENTICATE","sentence":"2FA = two-factor ___ .","a":"authentication","alts":["authentication"],"explain":"-ation"},
  {"type":"word_form","base":"MANAGE","sentence":"A password ___ stores all of them.","a":"manager","alts":["manager"],"explain":"-er"},
  {"type":"word_form","base":"PROTECT","sentence":"Add 2FA to ___ accounts.","a":"protect","alts":["protect"],"explain":"verb"},
  {"type":"key_word","original":"You should not write passwords on paper.","key":"DON'T","gap_template":"___ write passwords on paper.","a":"Don't","alts":["Don't"],"explain":""},
  {"type":"key_word","original":"Use 12 characters or more.","key":"AT","gap_template":"Use ___ 12 characters.","a":"at least","alts":["at least"],"explain":""},
  {"type":"key_word","original":"It is a good idea to enable 2FA.","key":"SHOULD","gap_template":"You ___ 2FA.","a":"should enable","alts":["should enable"],"explain":""},
  {"type":"key_word","original":"Don't share with anyone.","key":"NEVER","gap_template":"___ share with anyone.","a":"Never","alts":["Never"],"explain":""},
  {"type":"key_word","original":"Sharing the password is dangerous.","key":"DON'T","gap_template":"___ the password.","a":"Don't share","alts":["Don't share"],"explain":""}],
 11: [  # Mobile (object pronouns)
  {"type":"mc_cloze","sentence":"Call ___ when you arrive.","options":["I","me","my","mine"],"a":1,"explain":"obj."},
  {"type":"mc_cloze","sentence":"Send the file to ___ .","options":["he","him","his","he's"],"a":1,"explain":"obj."},
  {"type":"mc_cloze","sentence":"They support ___ .","options":["we","us","our","ours"],"a":1,"explain":"obj."},
  {"type":"mc_cloze","sentence":"I texted ___ yesterday.","options":["she","her","hers","she's"],"a":1,"explain":"obj."},
  {"type":"cloze","sentence":"Give the laptop to ___ .","a":"me","alts":["me"],"explain":"after prep."},
  {"type":"cloze","sentence":"The team trusts ___ .","a":"us","alts":["us"],"explain":"obj."},
  {"type":"cloze","sentence":"My boss helped ___ a lot.","a":"me","alts":["me"],"explain":"obj."},
  {"type":"cloze","sentence":"I sent ___ the report.","a":"them","alts":["them"],"explain":"obj."},
  {"type":"word_form","base":"MOBILE","sentence":"This is my work ___ .","a":"mobile","alts":["mobile"],"explain":"unchanged"},
  {"type":"word_form","base":"FINGER","sentence":"I unlock with my ___ .","a":"fingerprint","alts":["fingerprint"],"explain":"compound"},
  {"type":"word_form","base":"REMOTE","sentence":"They can ___ wipe the phone.","a":"remotely","alts":["remotely"],"explain":"-ly"},
  {"type":"word_form","base":"SECURE","sentence":"This phone is very ___ .","a":"secure","alts":["secure"],"explain":"adj"},
  {"type":"key_word","original":"He told me the news.","key":"ME","gap_template":"He told ___ news.","a":"me the","alts":["me the"],"explain":""},
  {"type":"key_word","original":"Call my colleagues now.","key":"THEM","gap_template":"Call ___ now.","a":"them","alts":["them"],"explain":""},
  {"type":"key_word","original":"This is my phone.","key":"MINE","gap_template":"This phone is ___ .","a":"mine","alts":["mine"],"explain":""},
  {"type":"key_word","original":"That is her laptop.","key":"HERS","gap_template":"That laptop is ___ .","a":"hers","alts":["hers"],"explain":""},
  {"type":"key_word","original":"Help us with the update.","key":"US","gap_template":"Could you help ___ ?","a":"us","alts":["us"],"explain":""}],
 12: [  # UI colors
  {"type":"mc_cloze","sentence":"Click the ___ button to stop.","options":["red big","big red","of red","red of"],"a":1,"explain":"size+col"},
  {"type":"mc_cloze","sentence":"It is a ___ icon.","options":["small grey","grey small","small of","grey of"],"a":0,"explain":"size+col"},
  {"type":"mc_cloze","sentence":"Use ___ for errors.","options":["red","reds","redly","reded"],"a":0,"explain":"adj"},
  {"type":"mc_cloze","sentence":"Green means ___ .","options":["danger","success","warning","error"],"a":1,"explain":""},
  {"type":"cloze","sentence":"The settings icon is ___ the top right.","a":"on","alts":["on","in"],"explain":"loc."},
  {"type":"cloze","sentence":"The error is ___ red text.","a":"in","alts":["in"],"explain":"in red"},
  {"type":"cloze","sentence":"A flat design is ___ minimalist.","a":"more","alts":["more"],"explain":"comparative"},
  {"type":"cloze","sentence":"Click ___ Help link.","a":"the","alts":["the"],"explain":"def. art."},
  {"type":"word_form","base":"WARN","sentence":"A yellow ___ icon appears.","a":"warning","alts":["warning"],"explain":"-ing"},
  {"type":"word_form","base":"SUCCESS","sentence":"Show a ___ message in green.","a":"success","alts":["success"],"explain":"noun"},
  {"type":"word_form","base":"DESIGN","sentence":"This is a flat ___ .","a":"design","alts":["design"],"explain":"noun"},
  {"type":"word_form","base":"COLOUR","sentence":"Use the right ___ .","a":"colour","alts":["colour","color"],"explain":""},
  {"type":"key_word","original":"The icon is small and grey.","key":"SMALL","gap_template":"It is a ___ grey icon.","a":"small","alts":["small"],"explain":"order"},
  {"type":"key_word","original":"Show a red message for errors.","key":"FOR","gap_template":"Use red ___ errors.","a":"for","alts":["for"],"explain":"purpose"},
  {"type":"key_word","original":"Press the green start button.","key":"PRESS","gap_template":"___ the green button.","a":"Press","alts":["Press"],"explain":"imp."},
  {"type":"key_word","original":"The header is dark blue.","key":"DARK","gap_template":"The header is ___ blue.","a":"dark","alts":["dark"],"explain":""},
  {"type":"key_word","original":"There is a help link.","key":"LINK","gap_template":"There is a help ___ .","a":"link","alts":["link"],"explain":""}],
 13: [  # Office tools (have to / need to)
  {"type":"mc_cloze","sentence":"I ___ send the report by 3 p.m.","options":["have to","has to","having to","had"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"You ___ buy Office, LibreOffice is free.","options":["don't have to","mustn't","cannot","need"],"a":0,"explain":"no obligation"},
  {"type":"mc_cloze","sentence":"I ___ check the formulas.","options":["need","need to","needs","needing"],"a":1,"explain":"need + to"},
  {"type":"mc_cloze","sentence":"Press Ctrl ___ to save.","options":["+S","S","-S","at S"],"a":0,"explain":""},
  {"type":"cloze","sentence":"Save ___ PDF before sending.","a":"as","alts":["as"],"explain":"format"},
  {"type":"cloze","sentence":"Use ___ formula =SUM.","a":"the","alts":["the"],"explain":"def."},
  {"type":"cloze","sentence":"Copy and ___ the cells.","a":"paste","alts":["paste"],"explain":""},
  {"type":"cloze","sentence":"Track ___ in Word.","a":"changes","alts":["changes"],"explain":""},
  {"type":"word_form","base":"PRESENT","sentence":"My ___ is tomorrow.","a":"presentation","alts":["presentation"],"explain":"-ation"},
  {"type":"word_form","base":"FORMULA","sentence":"=SUM is a ___ .","a":"formula","alts":["formula"],"explain":""},
  {"type":"word_form","base":"DOCUMENT","sentence":"Open the Word ___ .","a":"document","alts":["document"],"explain":""},
  {"type":"word_form","base":"COLLABORATE","sentence":"Real-time ___ in Office 365.","a":"collaboration","alts":["collaboration"],"explain":"-ation"},
  {"type":"key_word","original":"It is necessary to send by 3.","key":"HAVE","gap_template":"I ___ by 3.","a":"have to send","alts":["have to send"],"explain":""},
  {"type":"key_word","original":"It is not necessary to print it.","key":"DON'T","gap_template":"You ___ print it.","a":"don't have to","alts":["don't have to"],"explain":""},
  {"type":"key_word","original":"You must accept the EULA.","key":"MUST","gap_template":"You ___ accept the EULA.","a":"must","alts":["must"],"explain":""},
  {"type":"key_word","original":"It is required to log in.","key":"NEED","gap_template":"You ___ log in.","a":"need to","alts":["need to"],"explain":""},
  {"type":"key_word","original":"Save it as PDF, please.","key":"SAVE","gap_template":"Could you ___ PDF?","a":"save it as","alts":["save it as"],"explain":""}],
 14: [  # Email etiquette (politeness)
  {"type":"mc_cloze","sentence":"___ you send me the file?","options":["Do","Could","Are","Must"],"a":1,"explain":"polite"},
  {"type":"mc_cloze","sentence":"Thank you ___ your help.","options":["of","for","with","at"],"a":1,"explain":"FOR"},
  {"type":"mc_cloze","sentence":"___ regards,","options":["Best","Better","Bestly","Most best"],"a":0,"explain":"closing"},
  {"type":"mc_cloze","sentence":"Hi Ana, I ___ asking about the report.","options":["am","is","are","be"],"a":0,"explain":"1st sing"},
  {"type":"cloze","sentence":"Could you ___ today?","a":"reply","alts":["reply","respond"],"explain":""},
  {"type":"cloze","sentence":"I would ___ a quick reply.","a":"appreciate","alts":["appreciate"],"explain":"formal"},
  {"type":"cloze","sentence":"Find ___ the file.","a":"attached","alts":["attached"],"explain":"common"},
  {"type":"cloze","sentence":"Hi Marta, hope you ___ well.","a":"are","alts":["are"],"explain":"BE"},
  {"type":"word_form","base":"INFORM","sentence":"For your ___ , the meeting moved.","a":"information","alts":["information"],"explain":"-ation"},
  {"type":"word_form","base":"APPRECIATE","sentence":"I would ___ your help.","a":"appreciate","alts":["appreciate"],"explain":"verb"},
  {"type":"word_form","base":"REPLY","sentence":"A quick ___ would be great.","a":"reply","alts":["reply"],"explain":"noun"},
  {"type":"word_form","base":"ATTACH","sentence":"Find the ___ in the email.","a":"attachment","alts":["attachment"],"explain":"-ment"},
  {"type":"key_word","original":"Send me the file.","key":"COULD","gap_template":"___ send me the file?","a":"Could you","alts":["Could you"],"explain":""},
  {"type":"key_word","original":"I want to know if you can call.","key":"WONDER","gap_template":"I ___ if you can call.","a":"wonder","alts":["wonder"],"explain":""},
  {"type":"key_word","original":"Thanks for your time.","key":"FOR","gap_template":"Thank you ___ your time.","a":"for","alts":["for"],"explain":""},
  {"type":"key_word","original":"Hope you are well.","key":"HOPE","gap_template":"I ___ are well.","a":"hope you","alts":["hope you"],"explain":""},
  {"type":"key_word","original":"Looking forward to hearing back.","key":"FORWARD","gap_template":"Looking ___ to hearing back.","a":"forward","alts":["forward"],"explain":""}],
 15: [  # Time (preps at/on/in)
  {"type":"mc_cloze","sentence":"The meeting is ___ Monday.","options":["at","on","in","by"],"a":1,"explain":"day"},
  {"type":"mc_cloze","sentence":"It is ___ 10 a.m.","options":["at","on","in","by"],"a":0,"explain":"clock"},
  {"type":"mc_cloze","sentence":"The release is ___ June.","options":["at","on","in","by"],"a":2,"explain":"month"},
  {"type":"mc_cloze","sentence":"I joined ___ 2024.","options":["at","on","in","by"],"a":2,"explain":"year"},
  {"type":"cloze","sentence":"Are you free ___ Tuesday?","a":"on","alts":["on"],"explain":"day"},
  {"type":"cloze","sentence":"The standup is ___ 9.","a":"at","alts":["at"],"explain":"clock"},
  {"type":"cloze","sentence":"I will see you ___ the morning.","a":"in","alts":["in"],"explain":"period"},
  {"type":"cloze","sentence":"The deadline is ___ 30 May.","a":"on","alts":["on"],"explain":"date"},
  {"type":"word_form","base":"SCHEDULE","sentence":"My ___ is full.","a":"schedule","alts":["schedule"],"explain":""},
  {"type":"word_form","base":"MEET","sentence":"Today's ___ was long.","a":"meeting","alts":["meeting"],"explain":""},
  {"type":"word_form","base":"INVITE","sentence":"I sent the calendar ___ .","a":"invite","alts":["invite","invitation"],"explain":""},
  {"type":"word_form","base":"AVAILABLE","sentence":"What is your ___ ?","a":"availability","alts":["availability"],"explain":"-ility"},
  {"type":"key_word","original":"Let's meet at 11.","key":"AT","gap_template":"Let's meet ___ 11.","a":"at","alts":["at"],"explain":""},
  {"type":"key_word","original":"The retro is on Friday.","key":"FRIDAY","gap_template":"The retro is on ___ .","a":"Friday","alts":["Friday"],"explain":""},
  {"type":"key_word","original":"I am free on the weekend.","key":"AT","gap_template":"I am free ___ weekend.","a":"at the","alts":["at the"],"explain":"set phrase"},
  {"type":"key_word","original":"Can we move it to Wednesday?","key":"MOVE","gap_template":"Can we ___ to Wednesday?","a":"move it","alts":["move it"],"explain":""},
  {"type":"key_word","original":"Calendar invite is sent.","key":"SENT","gap_template":"The invite ___ .","a":"is sent","alts":["is sent","has been sent"],"explain":"passive"}],
 16: [  # Sizes (countable/uncountable)
  {"type":"mc_cloze","sentence":"How ___ RAM does it have?","options":["many","much","a many","a much"],"a":1,"explain":"unc."},
  {"type":"mc_cloze","sentence":"How ___ files are there?","options":["many","much","any","a"],"a":0,"explain":"count."},
  {"type":"mc_cloze","sentence":"I have ___ free space.","options":["many","much","a few","much of"],"a":1,"explain":"unc."},
  {"type":"mc_cloze","sentence":"There are ___ backups.","options":["a little","a few","much","many of"],"a":1,"explain":"count."},
  {"type":"cloze","sentence":"It has 1 TB ___ storage.","a":"of","alts":["of"],"explain":"OF"},
  {"type":"cloze","sentence":"My laptop ___ 16 GB of RAM.","a":"has","alts":["has"],"explain":""},
  {"type":"cloze","sentence":"The disk is ___ full.","a":"almost","alts":["almost","nearly"],"explain":""},
  {"type":"cloze","sentence":"I ___ have much memory left.","a":"don't","alts":["don't","do not"],"explain":""},
  {"type":"word_form","base":"STORE","sentence":"This SSD has plenty of ___ .","a":"storage","alts":["storage"],"explain":"-age"},
  {"type":"word_form","base":"MEMORY","sentence":"More ___ helps.","a":"memory","alts":["memory"],"explain":"unc."},
  {"type":"word_form","base":"CAPACITY","sentence":"Disk ___ is 1 TB.","a":"capacity","alts":["capacity"],"explain":""},
  {"type":"word_form","base":"RESOLVE","sentence":"Screen ___ is 4K.","a":"resolution","alts":["resolution"],"explain":"-tion"},
  {"type":"key_word","original":"How big is the file?","key":"SIZE","gap_template":"What is the ___ file?","a":"size of the","alts":["size of the"],"explain":""},
  {"type":"key_word","original":"It has 32 GB.","key":"OF","gap_template":"It has 32 GB ___ RAM.","a":"of","alts":["of"],"explain":""},
  {"type":"key_word","original":"Two USB ports are on the side.","key":"ARE","gap_template":"There ___ on the side.","a":"are two USB ports","alts":["are two USB ports"],"explain":""},
  {"type":"key_word","original":"There is little space left.","key":"LITTLE","gap_template":"There is ___ space left.","a":"little","alts":["little"],"explain":""},
  {"type":"key_word","original":"The screen is 16 inches wide.","key":"WIDE","gap_template":"It is 16 inches ___ .","a":"wide","alts":["wide"],"explain":""}],
 17: [  # Troubleshooting (sequence + because)
  {"type":"mc_cloze","sentence":"___ , restart the computer.","options":["First","One","Onlyone","Now"],"a":0,"explain":"sequence"},
  {"type":"mc_cloze","sentence":"___ , check the disk space.","options":["Then","Up","After","One"],"a":0,"explain":"sequence"},
  {"type":"mc_cloze","sentence":"It was slow ___ the disk was full.","options":["because","why","so","but"],"a":0,"explain":"reason"},
  {"type":"mc_cloze","sentence":"Have you tried turning ___ and on again?","options":["it off","off it","off","at off"],"a":0,"explain":"phrasal"},
  {"type":"cloze","sentence":"___ , clear the cache.","a":"Finally","alts":["Finally"],"explain":"end"},
  {"type":"cloze","sentence":"Why is it slow? ___ the disk is full.","a":"Because","alts":["Because"],"explain":"reason"},
  {"type":"cloze","sentence":"After ___ , try again.","a":"that","alts":["that"],"explain":""},
  {"type":"cloze","sentence":"Check the ___ message in the logs.","a":"error","alts":["error"],"explain":""},
  {"type":"word_form","base":"SOLVE","sentence":"Problem ___ !","a":"solved","alts":["solved"],"explain":"-ed"},
  {"type":"word_form","base":"FIX","sentence":"That is a quick ___ .","a":"fix","alts":["fix"],"explain":"noun"},
  {"type":"word_form","base":"REINSTALL","sentence":"___ the program if it fails.","a":"Reinstall","alts":["Reinstall"],"explain":"verb"},
  {"type":"word_form","base":"RESTART","sentence":"A ___ usually helps.","a":"restart","alts":["restart"],"explain":"noun"},
  {"type":"key_word","original":"My computer was slow because the disk was full.","key":"WHY","gap_template":"___ was it slow? Because the disk was full.","a":"Why","alts":["Why"],"explain":""},
  {"type":"key_word","original":"Restart it first.","key":"FIRST","gap_template":"___ , restart it.","a":"First","alts":["First"],"explain":""},
  {"type":"key_word","original":"Then check the disk.","key":"THEN","gap_template":"___ check the disk.","a":"Then","alts":["Then"],"explain":""},
  {"type":"key_word","original":"The cache also helps.","key":"TOO","gap_template":"The cache helps ___ .","a":"too","alts":["too"],"explain":""},
  {"type":"key_word","original":"It is fixed now.","key":"NOW","gap_template":"It is ___ .","a":"fixed now","alts":["fixed now"],"explain":""}],
 18: [  # IT jobs (comparatives)
  {"type":"mc_cloze","sentence":"Python is ___ than C++.","options":["easier","more easy","easyer","easyly"],"a":0,"explain":"-er"},
  {"type":"mc_cloze","sentence":"A senior is ___ paid than a junior.","options":["good","gooder","better","most"],"a":2,"explain":"irreg."},
  {"type":"mc_cloze","sentence":"Lima is ___ than Cusco.","options":["bigger","biger","big","most big"],"a":0,"explain":"-er + cons. doubling"},
  {"type":"mc_cloze","sentence":"My laptop is ___ than yours.","options":["fast","faster","fastest","more fast"],"a":1,"explain":"-er"},
  {"type":"cloze","sentence":"A SOC analyst is ___ stressful than a developer.","a":"more","alts":["more"],"explain":"long adj"},
  {"type":"cloze","sentence":"Linux is the ___ flexible OS.","a":"most","alts":["most"],"explain":"sup."},
  {"type":"cloze","sentence":"Java is older ___ Python.","a":"than","alts":["than"],"explain":"comp."},
  {"type":"cloze","sentence":"Cybersecurity pays ___ than support.","a":"more","alts":["more"],"explain":""},
  {"type":"word_form","base":"DEVELOP","sentence":"She is a ___ at a bank.","a":"developer","alts":["developer"],"explain":"-er"},
  {"type":"word_form","base":"LEAD","sentence":"He is a tech ___ .","a":"lead","alts":["lead"],"explain":""},
  {"type":"word_form","base":"ADMIN","sentence":"She is a system ___ .","a":"admin","alts":["admin","administrator"],"explain":""},
  {"type":"word_form","base":"SUPPORT","sentence":"He works in ___ .","a":"support","alts":["support"],"explain":""},
  {"type":"key_word","original":"Python is easier than C++.","key":"DIFFICULT","gap_template":"C++ is more ___ Python.","a":"difficult than","alts":["difficult than"],"explain":""},
  {"type":"key_word","original":"He is the best engineer.","key":"BEST","gap_template":"He is the ___ engineer.","a":"best","alts":["best"],"explain":"sup."},
  {"type":"key_word","original":"Pentesting pays well.","key":"WELL","gap_template":"Pentesting pays ___ .","a":"well","alts":["well"],"explain":"adv"},
  {"type":"key_word","original":"Java is older than Python.","key":"YOUNGER","gap_template":"Python is ___ Java.","a":"younger than","alts":["younger than"],"explain":""},
  {"type":"key_word","original":"This job is the most stressful.","key":"MOST","gap_template":"This job is the ___ stressful.","a":"most","alts":["most"],"explain":""}],
 19: [  # CV (past simple regular + last/ago)
  {"type":"mc_cloze","sentence":"I ___ at IBM last year.","options":["work","worked","working","works"],"a":1,"explain":"past"},
  {"type":"mc_cloze","sentence":"She ___ a project on AWS.","options":["delivered","deliver","delivers","delivering"],"a":0,"explain":"past"},
  {"type":"mc_cloze","sentence":"I graduated 5 years ___ .","options":["before","ago","since","ever"],"a":1,"explain":"AGO"},
  {"type":"mc_cloze","sentence":"She built two apps ___ year.","options":["last","ago","since","yesterday"],"a":0,"explain":"LAST"},
  {"type":"cloze","sentence":"Last month I ___ a certification.","a":"got","alts":["got"],"explain":"past"},
  {"type":"cloze","sentence":"She passed the exam 6 months ___ .","a":"ago","alts":["ago"],"explain":""},
  {"type":"cloze","sentence":"I ___ at Acme from 2020 to 2024.","a":"worked","alts":["worked"],"explain":""},
  {"type":"cloze","sentence":"My team ___ the migration last year.","a":"completed","alts":["completed","finished"],"explain":""},
  {"type":"word_form","base":"GRADUATE","sentence":"My ___ year was 2023.","a":"graduation","alts":["graduation"],"explain":"-tion"},
  {"type":"word_form","base":"CERTIFY","sentence":"I have an AWS ___ .","a":"certification","alts":["certification","certificate"],"explain":""},
  {"type":"word_form","base":"ACHIEVE","sentence":"This is my main ___ .","a":"achievement","alts":["achievement"],"explain":"-ment"},
  {"type":"word_form","base":"DELIVER","sentence":"On-time ___ matters.","a":"delivery","alts":["delivery"],"explain":"-y"},
  {"type":"key_word","original":"I joined IBM 2 years ago.","key":"FOR","gap_template":"I have worked at IBM ___ years.","a":"for two","alts":["for two","for 2"],"explain":""},
  {"type":"key_word","original":"She delivered three apps last year.","key":"DELIVERED","gap_template":"Last year she ___ apps.","a":"delivered three","alts":["delivered three"],"explain":""},
  {"type":"key_word","original":"He started as a junior in 2020.","key":"AS","gap_template":"He started ___ junior in 2020.","a":"as a","alts":["as a"],"explain":""},
  {"type":"key_word","original":"I have an AWS certification.","key":"GOT","gap_template":"I ___ an AWS certification.","a":"have got","alts":["have got"],"explain":""},
  {"type":"key_word","original":"My career started 5 years ago.","key":"AGO","gap_template":"It is 5 years ___ .","a":"ago","alts":["ago"],"explain":""}],
 20: [  # KET review
  {"type":"mc_cloze","sentence":"I ___ in security since 2024.","options":["work","am working","have worked","working"],"a":2,"explain":"PP"},
  {"type":"mc_cloze","sentence":"She ___ an analyst now.","options":["am","is","are","be"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"They ___ to AWS last year.","options":["migrate","migrated","migrating","is migrate"],"a":1,"explain":"past"},
  {"type":"mc_cloze","sentence":"It ___ encrypted with AES.","options":["am","is","are","be"],"a":1,"explain":"passive"},
  {"type":"cloze","sentence":"I am ___ for a senior role.","a":"applying","alts":["applying"],"explain":"-ing"},
  {"type":"cloze","sentence":"My next goal ___ B1.","a":"is","alts":["is"],"explain":""},
  {"type":"cloze","sentence":"Could you ___ that, please?","a":"repeat","alts":["repeat","say"],"explain":""},
  {"type":"cloze","sentence":"Yes, I would like ___ start.","a":"to","alts":["to"],"explain":""},
  {"type":"word_form","base":"COMPLETE","sentence":"I ___ A1 last month.","a":"completed","alts":["completed"],"explain":"past"},
  {"type":"word_form","base":"PREPARE","sentence":"My ___ takes 2 hours daily.","a":"preparation","alts":["preparation"],"explain":""},
  {"type":"word_form","base":"DAILY","sentence":"I do ___ exercises.","a":"daily","alts":["daily"],"explain":"adj"},
  {"type":"word_form","base":"SUCCEED","sentence":"I want to ___ in IT.","a":"succeed","alts":["succeed"],"explain":"verb"},
  {"type":"key_word","original":"I have studied for one year.","key":"ONE","gap_template":"It has been ___ year of study.","a":"one","alts":["one","a"],"explain":""},
  {"type":"key_word","original":"My goal is B2 in 2027.","key":"BY","gap_template":"I want to reach B2 ___ 2027.","a":"by","alts":["by"],"explain":""},
  {"type":"key_word","original":"I am ready for the exam.","key":"READY","gap_template":"I am ___ exam.","a":"ready for the","alts":["ready for the"],"explain":""},
  {"type":"key_word","original":"I will pass it.","key":"PASS","gap_template":"I will ___ .","a":"pass it","alts":["pass it"],"explain":""},
  {"type":"key_word","original":"Practice every day.","key":"DAILY","gap_template":"Practice ___ .","a":"daily","alts":["daily"],"explain":""}],
},
}

# A2 expansion (compact)
ADD["A2"] = {
 1:[  # IT jobs (PS vs PC)
  {"type":"mc_cloze","sentence":"Right now she ___ an alert.","options":["investigates","is investigating","investigate","investigated"],"a":1,"explain":"now → cont."},
  {"type":"mc_cloze","sentence":"He ___ tickets every day.","options":["close","closes","closing","closed"],"a":1,"explain":"3rd sing."},
  {"type":"mc_cloze","sentence":"They ___ on a migration this week.","options":["work","worked","are working","works"],"a":2,"explain":"this week"},
  {"type":"mc_cloze","sentence":"She ___ a team of 5.","options":["lead","leads","leading","is lead"],"a":1,"explain":"3rd sing."},
  {"type":"cloze","sentence":"Look! He ___ the firewall now.","a":"is configuring","alts":["is configuring"],"explain":"now"},
  {"type":"cloze","sentence":"The team ___ daily standups.","a":"has","alts":["has"],"explain":""},
  {"type":"cloze","sentence":"At the moment we ___ to AWS.","a":"are migrating","alts":["are migrating"],"explain":""},
  {"type":"cloze","sentence":"A SOC analyst ___ alerts on screens.","a":"watches","alts":["watches"],"explain":"3rd sing."},
  {"type":"word_form","base":"RESPONSIBLE","sentence":"She has full ___ for security.","a":"responsibility","alts":["responsibility"],"explain":""},
  {"type":"word_form","base":"LEAD","sentence":"He is the team ___ .","a":"lead","alts":["lead"],"explain":""},
  {"type":"word_form","base":"INVESTIGATE","sentence":"The ___ takes hours.","a":"investigation","alts":["investigation"],"explain":""},
  {"type":"word_form","base":"DEVELOP","sentence":"Junior ___ earn 3000 soles.","a":"developers","alts":["developers"],"explain":""},
  {"type":"key_word","original":"I lead the team.","key":"LEADER","gap_template":"I am the team ___ .","a":"leader","alts":["leader"],"explain":""},
  {"type":"key_word","original":"She is responsible for ops.","key":"FOR","gap_template":"She is responsible ___ ops.","a":"for","alts":["for"],"explain":""},
  {"type":"key_word","original":"He is in charge of security.","key":"OF","gap_template":"He is in charge ___ security.","a":"of","alts":["of"],"explain":""},
  {"type":"key_word","original":"They are testing right now.","key":"NOW","gap_template":"They ___ test.","a":"are now testing","alts":["are now testing","are testing now"],"explain":""},
  {"type":"key_word","original":"I report to my manager.","key":"TO","gap_template":"I report ___ manager.","a":"to my","alts":["to my"],"explain":""}],
 2:[  # Career past simple
  {"type":"mc_cloze","sentence":"In 2019 I ___ in Arequipa.","options":["worked","work","working","is work"],"a":0,"explain":"past"},
  {"type":"mc_cloze","sentence":"She ___ to Lima last year.","options":["move","moves","moved","moving"],"a":2,"explain":"past"},
  {"type":"mc_cloze","sentence":"They ___ AWS in 2022.","options":["adopt","adopted","adopting","adopts"],"a":1,"explain":"past"},
  {"type":"mc_cloze","sentence":"He ___ his English a lot.","options":["improve","improves","improved","is improve"],"a":2,"explain":"past"},
  {"type":"cloze","sentence":"Last month she ___ her certification.","a":"got","alts":["got"],"explain":"past irreg."},
  {"type":"cloze","sentence":"In 2020 we ___ remote work.","a":"started","alts":["started","began"],"explain":"past"},
  {"type":"cloze","sentence":"He didn't ___ AWS before 2022.","a":"know","alts":["know","use"],"explain":"after didn't"},
  {"type":"cloze","sentence":"Did you ___ the migration?","a":"complete","alts":["complete","finish"],"explain":"after did"},
  {"type":"word_form","base":"MOVE","sentence":"My ___ to Lima was last year.","a":"move","alts":["move"],"explain":""},
  {"type":"word_form","base":"GROW","sentence":"My salary ___ over 3 years.","a":"grew","alts":["grew"],"explain":"past"},
  {"type":"word_form","base":"PROMOTE","sentence":"She got a ___ in 2024.","a":"promotion","alts":["promotion"],"explain":""},
  {"type":"word_form","base":"LEARN","sentence":"I ___ a lot at the bank.","a":"learned","alts":["learned","learnt"],"explain":""},
  {"type":"key_word","original":"I joined in 2019.","key":"AGO","gap_template":"I joined ___ years ago.","a":"several","alts":["several","many"],"explain":""},
  {"type":"key_word","original":"She started at the helpdesk.","key":"STARTED","gap_template":"She ___ helpdesk.","a":"started at the","alts":["started at the"],"explain":""},
  {"type":"key_word","original":"He moved to a cloud company.","key":"COMPANY","gap_template":"He moved to a cloud ___ .","a":"company","alts":["company"],"explain":""},
  {"type":"key_word","original":"I changed jobs in 2022.","key":"IN","gap_template":"I changed jobs ___ 2022.","a":"in","alts":["in"],"explain":""},
  {"type":"key_word","original":"She did not have AWS experience.","key":"DIDN'T","gap_template":"She ___ have AWS experience.","a":"didn't","alts":["didn't"],"explain":""}],
 3:[  # OS comparatives
  {"type":"mc_cloze","sentence":"Linux is ___ flexible than Windows.","options":["more","most","much","many"],"a":0,"explain":"long adj"},
  {"type":"mc_cloze","sentence":"macOS is the ___ elegant.","options":["more","most","much","many"],"a":1,"explain":"sup."},
  {"type":"mc_cloze","sentence":"Windows has ___ games.","options":["more","most","many","much"],"a":0,"explain":"more+plural"},
  {"type":"mc_cloze","sentence":"Linux is ___ secure than Windows.","options":["more","most","much","best"],"a":0,"explain":""},
  {"type":"cloze","sentence":"More than 90% of servers ___ Linux.","a":"run","alts":["run"],"explain":""},
  {"type":"cloze","sentence":"macOS is only ___ Mac devices.","a":"for","alts":["for"],"explain":""},
  {"type":"cloze","sentence":"Windows is the ___ popular for offices.","a":"most","alts":["most"],"explain":""},
  {"type":"cloze","sentence":"Linux has the ___ open source.","a":"most","alts":["most"],"explain":""},
  {"type":"word_form","base":"FLEXIBLE","sentence":"Its main ___ is the kernel.","a":"flexibility","alts":["flexibility"],"explain":""},
  {"type":"word_form","base":"SECURE","sentence":"Linux ___ is well known.","a":"security","alts":["security"],"explain":""},
  {"type":"word_form","base":"POPULAR","sentence":"Windows ___ is high.","a":"popularity","alts":["popularity"],"explain":""},
  {"type":"word_form","base":"OPERATE","sentence":"Choose your ___ system.","a":"operating","alts":["operating"],"explain":""},
  {"type":"key_word","original":"Linux is more flexible than Windows.","key":"AS","gap_template":"Windows is not ___ Linux.","a":"as flexible as","alts":["as flexible as"],"explain":""},
  {"type":"key_word","original":"macOS is better designed than Windows.","key":"DESIGN","gap_template":"macOS has a better ___ .","a":"design","alts":["design"],"explain":""},
  {"type":"key_word","original":"Linux is the safest of the three.","key":"SAFER","gap_template":"Linux is ___ Windows.","a":"safer than","alts":["safer than"],"explain":""},
  {"type":"key_word","original":"All systems must be updated.","key":"REGULARLY","gap_template":"All must be updated ___ .","a":"regularly","alts":["regularly"],"explain":""},
  {"type":"key_word","original":"Pick Windows if you are new.","key":"START","gap_template":"___ with Windows if you are new.","a":"Start","alts":["Start"],"explain":""}],
 4:[  # Installing safely
  {"type":"mc_cloze","sentence":"You ___ download from official sites.","options":["have","have to","must to","needs"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"___ , go to the official website.","options":["First","One","Up","Now"],"a":0,"explain":"sequence"},
  {"type":"mc_cloze","sentence":"___ , verify the SHA-256 hash.","options":["Then","After of","One","Soon"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"Installers on Linux end in .deb or ___ .","options":[".dmg",".exe",".rpm",".jpg"],"a":2,"explain":""},
  {"type":"cloze","sentence":"Always read each ___ carefully.","a":"screen","alts":["screen"],"explain":""},
  {"type":"cloze","sentence":"Uncheck the boxes ___ extra software.","a":"for","alts":["for"],"explain":""},
  {"type":"cloze","sentence":"On Windows the file ends ___ .exe.","a":"in","alts":["in"],"explain":""},
  {"type":"cloze","sentence":"You ___ administrator rights.","a":"need","alts":["need"],"explain":""},
  {"type":"word_form","base":"INSTALL","sentence":"Run the ___ as admin.","a":"installer","alts":["installer"],"explain":""},
  {"type":"word_form","base":"VERIFY","sentence":"Hash ___ matters.","a":"verification","alts":["verification"],"explain":""},
  {"type":"word_form","base":"MALICIOUS","sentence":"Avoid ___ software.","a":"malicious","alts":["malicious"],"explain":"adj"},
  {"type":"word_form","base":"REPACKAGE","sentence":"Third-party sites ___ installers.","a":"repackage","alts":["repackage"],"explain":""},
  {"type":"key_word","original":"Don't use third-party sites.","key":"NEVER","gap_template":"___ third-party sites.","a":"Never use","alts":["Never use"],"explain":""},
  {"type":"key_word","original":"Verifying the hash is mandatory.","key":"MUST","gap_template":"You ___ the hash.","a":"must verify","alts":["must verify"],"explain":""},
  {"type":"key_word","original":"You don't need to print the EULA.","key":"DON'T","gap_template":"You ___ print the EULA.","a":"don't have to","alts":["don't have to"],"explain":""},
  {"type":"key_word","original":"Restart only if it asks.","key":"IF","gap_template":"Restart ___ asks.","a":"if it","alts":["if it"],"explain":""},
  {"type":"key_word","original":"Test the program after install.","key":"TEST","gap_template":"___ the program after install.","a":"Test","alts":["Test"],"explain":""}],
 5:[  # Browsers
  {"type":"mc_cloze","sentence":"You ___ keep the browser updated.","options":["should","must to","have","need"],"a":0,"explain":"advice"},
  {"type":"mc_cloze","sentence":"Firefox is famous ___ privacy.","options":["of","by","for","at"],"a":2,"explain":"FOR"},
  {"type":"mc_cloze","sentence":"You ___ install random extensions.","options":["should","shouldn't","not","mustn't to"],"a":1,"explain":"neg adv."},
  {"type":"mc_cloze","sentence":"Chrome has the ___ market share.","options":["bigger","biggest","more","most of"],"a":1,"explain":"sup."},
  {"type":"cloze","sentence":"Use a VPN ___ public Wi-Fi.","a":"on","alts":["on"],"explain":""},
  {"type":"cloze","sentence":"Edge integrates ___ with Microsoft 365.","a":"well","alts":["well"],"explain":"adv"},
  {"type":"cloze","sentence":"Incognito doesn't ___ history.","a":"save","alts":["save","keep"],"explain":""},
  {"type":"cloze","sentence":"Safari is fast ___ Apple devices.","a":"on","alts":["on"],"explain":""},
  {"type":"word_form","base":"PRIVATE","sentence":"Firefox focuses on ___ .","a":"privacy","alts":["privacy"],"explain":""},
  {"type":"word_form","base":"TRACK","sentence":"Tracking ___ blocks ads.","a":"protection","alts":["protection"],"explain":""},
  {"type":"word_form","base":"EXTEND","sentence":"Install the ___ from the store.","a":"extension","alts":["extension"],"explain":""},
  {"type":"word_form","base":"DEFEND","sentence":"Browser updates are a ___ .","a":"defence","alts":["defence","defense"],"explain":""},
  {"type":"key_word","original":"It is a good idea to use a VPN.","key":"SHOULD","gap_template":"You ___ a VPN.","a":"should use","alts":["should use"],"explain":""},
  {"type":"key_word","original":"Don't install random extensions.","key":"OUGHT","gap_template":"You ___ install random extensions.","a":"ought not to","alts":["ought not to"],"explain":""},
  {"type":"key_word","original":"Chrome dominates the market.","key":"BIGGEST","gap_template":"Chrome has the ___ share.","a":"biggest","alts":["biggest"],"explain":""},
  {"type":"key_word","original":"Update the browser, please.","key":"UPDATE","gap_template":"Please ___ browser.","a":"update the","alts":["update the"],"explain":""},
  {"type":"key_word","original":"Tor offers real privacy.","key":"REAL","gap_template":"Tor offers ___ privacy.","a":"real","alts":["real"],"explain":""}],
 6:[  # Social media (must/mustn't/can't)
  {"type":"mc_cloze","sentence":"You ___ share login codes.","options":["mustn't","must","can","should to"],"a":0,"explain":"prohib."},
  {"type":"mc_cloze","sentence":"You ___ post customer data.","options":["can","cannot","must","need"],"a":1,"explain":"prohib."},
  {"type":"mc_cloze","sentence":"Employees ___ post negative comments.","options":["mustn't","must","can","need"],"a":0,"explain":"policy"},
  {"type":"mc_cloze","sentence":"Check your settings ___ six months.","options":["any","every","some","each of"],"a":1,"explain":"every"},
  {"type":"cloze","sentence":"Be careful about ___ you post.","a":"what","alts":["what"],"explain":""},
  {"type":"cloze","sentence":"Block the user ___ harassment.","a":"for","alts":["for"],"explain":""},
  {"type":"cloze","sentence":"Report the ___ to the platform.","a":"post","alts":["post","abuse","content"],"explain":""},
  {"type":"cloze","sentence":"Privacy settings change ___ time.","a":"over","alts":["over","with"],"explain":""},
  {"type":"word_form","base":"PRIVATE","sentence":"Review your ___ settings.","a":"privacy","alts":["privacy"],"explain":""},
  {"type":"word_form","base":"PROFESSIONAL","sentence":"This is your ___ profile.","a":"professional","alts":["professional"],"explain":""},
  {"type":"word_form","base":"NEGATIVE","sentence":"Avoid ___ comments.","a":"negative","alts":["negative"],"explain":""},
  {"type":"word_form","base":"REPUTE","sentence":"Posts affect your ___ .","a":"reputation","alts":["reputation"],"explain":""},
  {"type":"key_word","original":"It is forbidden to share login codes.","key":"MUSTN'T","gap_template":"You ___ share login codes.","a":"mustn't","alts":["mustn't"],"explain":""},
  {"type":"key_word","original":"You are not allowed to post photos.","key":"CAN'T","gap_template":"You ___ post photos.","a":"can't","alts":["can't"],"explain":""},
  {"type":"key_word","original":"Always ask before tagging.","key":"ASK","gap_template":"Always ___ tagging.","a":"ask before","alts":["ask before"],"explain":""},
  {"type":"key_word","original":"It is necessary to review settings.","key":"NEED","gap_template":"You ___ review settings.","a":"need to","alts":["need to"],"explain":""},
  {"type":"key_word","original":"Posts can affect your job.","key":"AFFECT","gap_template":"Posts ___ your job.","a":"can affect","alts":["can affect"],"explain":""}],
 7:[  # Networks (adverbs of manner)
  {"type":"mc_cloze","sentence":"The router reboots ___ .","options":["quick","quickly","more quick","quick of"],"a":1,"explain":"-ly"},
  {"type":"mc_cloze","sentence":"This router works ___ .","options":["good","goodly","well","best"],"a":2,"explain":"irreg. adv"},
  {"type":"mc_cloze","sentence":"The page loads ___ today.","options":["slow","slowly","more slow","slow of"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"Configure the firewall ___ .","options":["careful","carefully","more careful","of careful"],"a":1,"explain":""},
  {"type":"cloze","sentence":"Data travels ___ on fibre.","a":"fast","alts":["fast"],"explain":"irreg."},
  {"type":"cloze","sentence":"The signal is ___ in the garage.","a":"weak","alts":["weak"],"explain":""},
  {"type":"cloze","sentence":"The Wi-Fi works ___ in the morning.","a":"well","alts":["well"],"explain":""},
  {"type":"cloze","sentence":"Move ___ to the router.","a":"closer","alts":["closer"],"explain":""},
  {"type":"word_form","base":"CONNECT","sentence":"My ___ is unstable.","a":"connection","alts":["connection"],"explain":""},
  {"type":"word_form","base":"WIRELESS","sentence":"Use a ___ network.","a":"wireless","alts":["wireless"],"explain":""},
  {"type":"word_form","base":"SIGN","sentence":"The ___ is weak.","a":"signal","alts":["signal"],"explain":""},
  {"type":"word_form","base":"CONFIGURE","sentence":"Router ___ takes 5 minutes.","a":"configuration","alts":["configuration"],"explain":""},
  {"type":"key_word","original":"It loads slowly.","key":"SLOW","gap_template":"It is ___ today.","a":"slow","alts":["slow"],"explain":"adj"},
  {"type":"key_word","original":"He configured it carefully.","key":"CARE","gap_template":"He configured it ___ .","a":"with care","alts":["with care","carefully"],"explain":""},
  {"type":"key_word","original":"Change the default password.","key":"DEFAULT","gap_template":"Change the ___ password.","a":"default","alts":["default"],"explain":""},
  {"type":"key_word","original":"The Wi-Fi works well.","key":"WORKS","gap_template":"The Wi-Fi ___ .","a":"works well","alts":["works well"],"explain":""},
  {"type":"key_word","original":"The signal is bad.","key":"BAD","gap_template":"The signal is ___ .","a":"bad","alts":["bad"],"explain":""}],
 8:[  # Mobile (going to)
  {"type":"mc_cloze","sentence":"I ___ install MDM today.","options":["will","am going to","go to","is going"],"a":1,"explain":"plan"},
  {"type":"mc_cloze","sentence":"We ___ require 2FA next month.","options":["are going to","goes to","will go to","were going to"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"She ___ enrol her phone.","options":["going","is going to","goes","go"],"a":1,"explain":""},
  {"type":"mc_cloze","sentence":"They ___ deploy on Friday.","options":["going","is going","are going to","goes to"],"a":2,"explain":""},
  {"type":"cloze","sentence":"I am going to ___ Face ID.","a":"set","alts":["set","enable","activate"],"explain":""},
  {"type":"cloze","sentence":"We are not going to ___ personal apps.","a":"install","alts":["install","allow"],"explain":""},
  {"type":"cloze","sentence":"Are you going ___ enrol?","a":"to","alts":["to"],"explain":""},
  {"type":"cloze","sentence":"The phone is going to ___ next week.","a":"arrive","alts":["arrive","ship"],"explain":""},
  {"type":"word_form","base":"ENROL","sentence":"Device ___ takes minutes.","a":"enrolment","alts":["enrolment","enrollment"],"explain":""},
  {"type":"word_form","base":"BIOMETRIC","sentence":"Use ___ login.","a":"biometric","alts":["biometric"],"explain":""},
  {"type":"word_form","base":"REMOTE","sentence":"They can wipe it ___ .","a":"remotely","alts":["remotely"],"explain":""},
  {"type":"word_form","base":"DEVICE","sentence":"MDM = mobile ___ management.","a":"device","alts":["device"],"explain":""},
  {"type":"key_word","original":"My plan is to enrol the phone.","key":"GOING","gap_template":"I ___ enrol the phone.","a":"am going to","alts":["am going to"],"explain":""},
  {"type":"key_word","original":"We won't allow jailbreak.","key":"GOING","gap_template":"We are ___ allow jailbreak.","a":"not going to","alts":["not going to"],"explain":""},
  {"type":"key_word","original":"Look — they will deploy soon.","key":"SOON","gap_template":"They are going to deploy ___ .","a":"soon","alts":["soon"],"explain":""},
  {"type":"key_word","original":"Plans for next month include MFA.","key":"INCLUDE","gap_template":"Next month plans ___ MFA.","a":"include","alts":["include"],"explain":""},
  {"type":"key_word","original":"I will read the AUP.","key":"GOING","gap_template":"I ___ the AUP.","a":"am going to read","alts":["am going to read"],"explain":""}],
 9:[  # Cloud (how much/many)
  {"type":"mc_cloze","sentence":"___ space do we have left?","options":["How many","How much","How","Much"],"a":1,"explain":"unc."},
  {"type":"mc_cloze","sentence":"___ files do we own?","options":["How many","How much","How","Many"],"a":0,"explain":"count."},
  {"type":"mc_cloze","sentence":"There are ___ old backups.","options":["a little","a few","much","a many"],"a":1,"explain":"count."},
  {"type":"mc_cloze","sentence":"We have ___ free space.","options":["a few","a little","many","not much of"],"a":1,"explain":"unc."},
  {"type":"cloze","sentence":"The plan has 5 TB ___ storage.","a":"of","alts":["of"],"explain":""},
  {"type":"cloze","sentence":"Versioning lets us ___ files.","a":"restore","alts":["restore","recover"],"explain":""},
  {"type":"cloze","sentence":"Permissions changed ___ the security team.","a":"to","alts":["to"],"explain":""},
  {"type":"cloze","sentence":"Cold storage is ___ cheaper.","a":"much","alts":["much"],"explain":""},
  {"type":"word_form","base":"VERSION","sentence":"Enable ___ for safety.","a":"versioning","alts":["versioning"],"explain":""},
  {"type":"word_form","base":"PERMIT","sentence":"Review ___ regularly.","a":"permissions","alts":["permissions"],"explain":""},
  {"type":"word_form","base":"COMPETE","sentence":"Move to a ___ at lower price.","a":"competitor","alts":["competitor"],"explain":""},
  {"type":"word_form","base":"DISCIPLINE","sentence":"___ saves a lot of money.","a":"Discipline","alts":["Discipline"],"explain":""},
  {"type":"key_word","original":"We have 5 TB total.","key":"OF","gap_template":"We have 5 TB ___ storage.","a":"of","alts":["of"],"explain":""},
  {"type":"key_word","original":"Most files are old.","key":"OLD","gap_template":"Most files ___ years.","a":"are old by","alts":["are old by","are old after"],"explain":""},
  {"type":"key_word","original":"Only the security team has access.","key":"ONLY","gap_template":"___ has access.","a":"Only the security team","alts":["Only the security team"],"explain":""},
  {"type":"key_word","original":"How big is our storage?","key":"MUCH","gap_template":"How ___ storage do we have?","a":"much","alts":["much"],"explain":""},
  {"type":"key_word","original":"We are switching to a competitor.","key":"MOVE","gap_template":"We are going to ___ competitor.","a":"move to a","alts":["move to a"],"explain":""}],
 10:[  # Email (would you mind)
  {"type":"mc_cloze","sentence":"Would you mind ___ the draft?","options":["send","sending","to send","sent"],"a":1,"explain":"+ -ing"},
  {"type":"mc_cloze","sentence":"Could you ___ confirm by 5?","options":["possibly","possible","must","need"],"a":0,"explain":"adv"},
  {"type":"mc_cloze","sentence":"Please find ___ the file.","options":["attach","attached","attaching","to attach"],"a":1,"explain":"-ed"},
  {"type":"mc_cloze","sentence":"As ___ our discussion, we agreed.","options":["per","at","on","by"],"a":0,"explain":""},
  {"type":"cloze","sentence":"Following ___ from Monday, …","a":"up","alts":["up"],"explain":""},
  {"type":"cloze","sentence":"I would ___ a quick reply.","a":"appreciate","alts":["appreciate"],"explain":""},
  {"type":"cloze","sentence":"Hope you ___ well.","a":"are","alts":["are"],"explain":""},
  {"type":"cloze","sentence":"Thank you ___ your time.","a":"for","alts":["for"],"explain":""},
  {"type":"word_form","base":"FOLLOW","sentence":"This is a ___ email.","a":"follow-up","alts":["follow-up","followup"],"explain":""},
  {"type":"word_form","base":"CONFIRM","sentence":"I need ___ from you.","a":"confirmation","alts":["confirmation"],"explain":""},
  {"type":"word_form","base":"SIGN","sentence":"We need ___ -off from legal.","a":"sign","alts":["sign"],"explain":""},
  {"type":"word_form","base":"REGARD","sentence":"Best ___ ,","a":"regards","alts":["regards"],"explain":""},
  {"type":"key_word","original":"Send the draft, please.","key":"MIND","gap_template":"Would you ___ draft?","a":"mind sending the","alts":["mind sending the"],"explain":""},
  {"type":"key_word","original":"Is it possible to confirm today?","key":"POSSIBLY","gap_template":"Could you ___ today?","a":"possibly confirm","alts":["possibly confirm"],"explain":""},
  {"type":"key_word","original":"Find the plan attached.","key":"ATTACHED","gap_template":"Please find ___ plan.","a":"attached the","alts":["attached the"],"explain":""},
  {"type":"key_word","original":"As we discussed, we agreed.","key":"PER","gap_template":"As ___ our discussion, we agreed.","a":"per","alts":["per"],"explain":""},
  {"type":"key_word","original":"Thanks for replying quickly.","key":"QUICK","gap_template":"Thanks for the ___ .","a":"quick reply","alts":["quick reply"],"explain":""}],
 11:[  # Meetings (used to)
  {"type":"mc_cloze","sentence":"We ___ meet in person.","options":["used to","use to","using","were used to"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"I ___ turn on the camera.","options":["didn't use to","didn't used to","not use","don't used to"],"a":0,"explain":"neg"},
  {"type":"mc_cloze","sentence":"___ you use to come to the office?","options":["Did","Do","Are","Were"],"a":0,"explain":"q"},
  {"type":"mc_cloze","sentence":"They ___ a coffee machine here.","options":["used to have","use to have","using to have","are used to"],"a":0,"explain":""},
  {"type":"cloze","sentence":"We didn't use ___ share screens.","a":"to","alts":["to"],"explain":""},
  {"type":"cloze","sentence":"Did you use ___ work on-site?","a":"to","alts":["to"],"explain":""},
  {"type":"cloze","sentence":"My team used ___ have a standup at 9.","a":"to","alts":["to"],"explain":""},
  {"type":"cloze","sentence":"Now we ___ hybrid meetings.","a":"prefer","alts":["prefer","have"],"explain":""},
  {"type":"word_form","base":"HYBRID","sentence":"We work in a ___ model.","a":"hybrid","alts":["hybrid"],"explain":""},
  {"type":"word_form","base":"REMOTE","sentence":"___ work changed everything.","a":"Remote","alts":["Remote"],"explain":""},
  {"type":"word_form","base":"SHARE","sentence":"___ screen now.","a":"Share","alts":["Share"],"explain":""},
  {"type":"word_form","base":"PANDEMIC","sentence":"The ___ changed routines.","a":"pandemic","alts":["pandemic"],"explain":""},
  {"type":"key_word","original":"In the past we met in person.","key":"USED","gap_template":"We ___ in person.","a":"used to meet","alts":["used to meet"],"explain":""},
  {"type":"key_word","original":"I never turned on the camera before.","key":"NEVER","gap_template":"I ___ on the camera.","a":"never used to turn","alts":["never used to turn"],"explain":""},
  {"type":"key_word","original":"Did you have a coffee machine?","key":"USED","gap_template":"Did you ___ coffee machine?","a":"used to have a","alts":["use to have a","used to have a"],"explain":""},
  {"type":"key_word","original":"We work hybrid now.","key":"NOW","gap_template":"We ___ hybrid.","a":"now work","alts":["now work","work hybrid now"],"explain":""},
  {"type":"key_word","original":"Standups should be 15 minutes.","key":"SHORTER","gap_template":"Standups should be ___ 15 minutes.","a":"no longer than","alts":["no longer than","shorter than"],"explain":""}],
 12:[  # Reporting (1st conditional)
  {"type":"mc_cloze","sentence":"If the disk ___ full, the system freezes.","options":["will be","is","was","be"],"a":1,"explain":"if + present"},
  {"type":"mc_cloze","sentence":"If support replies, I ___ thank them.","options":["will","would","do","am"],"a":0,"explain":"result"},
  {"type":"mc_cloze","sentence":"If you restart, it ___ work again.","options":["will","would","does","is"],"a":0,"explain":"result"},
  {"type":"mc_cloze","sentence":"If the patch fails, we ___ rollback.","options":["will","would","are","do"],"a":0,"explain":""},
  {"type":"cloze","sentence":"If you ___ the password, reset it.","a":"forget","alts":["forget"],"explain":"if-clause"},
  {"type":"cloze","sentence":"The ticket ___ the error message.","a":"includes","alts":["includes"],"explain":""},
  {"type":"cloze","sentence":"It started ___ morning at 9.","a":"this","alts":["this"],"explain":""},
  {"type":"cloze","sentence":"I already ___ three things.","a":"tried","alts":["tried"],"explain":"PP intro"},
  {"type":"word_form","base":"CONNECT","sentence":"Cannot ___ to the server.","a":"connect","alts":["connect"],"explain":""},
  {"type":"word_form","base":"BACKUP","sentence":"Use the phone as a ___ .","a":"backup","alts":["backup","back-up"],"explain":""},
  {"type":"word_form","base":"REPORT","sentence":"This is a clear ___ .","a":"report","alts":["report"],"explain":""},
  {"type":"word_form","base":"CRITICAL","sentence":"This is a ___ issue.","a":"critical","alts":["critical"],"explain":""},
  {"type":"key_word","original":"If you patch, the bug goes away.","key":"PATCH","gap_template":"If you ___ , the bug goes away.","a":"patch","alts":["patch"],"explain":""},
  {"type":"key_word","original":"My laptop ID is LP-4892.","key":"ID","gap_template":"The ___ LP-4892.","a":"ID is","alts":["ID is"],"explain":""},
  {"type":"key_word","original":"Outlook does not work.","key":"DOESN'T","gap_template":"Outlook ___ work.","a":"doesn't","alts":["doesn't"],"explain":""},
  {"type":"key_word","original":"I tried Wi-Fi, restart, and the phone.","key":"TRIED","gap_template":"I ___ three things.","a":"tried","alts":["tried"],"explain":""},
  {"type":"key_word","original":"I have an important meeting at 3.","key":"AT","gap_template":"My meeting is ___ 3.","a":"at","alts":["at"],"explain":""}],
 13:[  # CIA triad (passive simple)
  {"type":"mc_cloze","sentence":"Passwords ___ as hashes.","options":["store","stored","are stored","is stored"],"a":2,"explain":"passive pl."},
  {"type":"mc_cloze","sentence":"The data ___ encrypted.","options":["was","were","being","be"],"a":0,"explain":"sing"},
  {"type":"mc_cloze","sentence":"Logs ___ reviewed daily.","options":["should be","should","ought","must to"],"a":0,"explain":"modal pass"},
  {"type":"mc_cloze","sentence":"Files ___ before exfiltration.","options":["encrypted","were encrypted","encrypts","are encrypt"],"a":1,"explain":""},
  {"type":"cloze","sentence":"Confidentiality ___ that data is private.","a":"means","alts":["means"],"explain":""},
  {"type":"cloze","sentence":"Integrity is ___ to detect.","a":"hard","alts":["hard","difficult"],"explain":""},
  {"type":"cloze","sentence":"Availability is lost when DDoS ___ .","a":"happens","alts":["happens","occurs"],"explain":""},
  {"type":"cloze","sentence":"Every control is a ___ .","a":"trade-off","alts":["trade-off","tradeoff"],"explain":""},
  {"type":"word_form","base":"INTEGRATE","sentence":"___ matters as much as confidentiality.","a":"Integrity","alts":["Integrity"],"explain":""},
  {"type":"word_form","base":"AVAILABLE","sentence":"___ is the third pillar.","a":"Availability","alts":["Availability"],"explain":""},
  {"type":"word_form","base":"PRIVATE","sentence":"___ is enforced by access controls.","a":"Privacy","alts":["Privacy"],"explain":""},
  {"type":"word_form","base":"SIGNATURE","sentence":"Digital ___ verify integrity.","a":"signatures","alts":["signatures"],"explain":""},
  {"type":"key_word","original":"Sensitive data must be encrypted.","key":"BE","gap_template":"Sensitive data must ___ encrypted.","a":"be","alts":["be"],"explain":""},
  {"type":"key_word","original":"Hashes prevent password theft.","key":"PREVENT","gap_template":"Hashes ___ theft.","a":"prevent password","alts":["prevent password"],"explain":""},
  {"type":"key_word","original":"DDoS attacks availability.","key":"AVAILABILITY","gap_template":"DDoS attacks ___ .","a":"availability","alts":["availability"],"explain":""},
  {"type":"key_word","original":"Checksums verify integrity.","key":"VERIFY","gap_template":"Checksums ___ integrity.","a":"verify","alts":["verify"],"explain":""},
  {"type":"key_word","original":"It is a balance.","key":"TRADE","gap_template":"It is a ___ .","a":"trade-off","alts":["trade-off"],"explain":""}],
 14:[  # Phishing (2nd conditional)
  {"type":"mc_cloze","sentence":"If I ___ this email, I would report it.","options":["receive","received","would receive","am"],"a":1,"explain":"past simple"},
  {"type":"mc_cloze","sentence":"If the URL ___ legitimate, you could click.","options":["is","were","would be","being"],"a":1,"explain":"WERE"},
  {"type":"mc_cloze","sentence":"What ___ you do if the bank emailed?","options":["will","would","do","are"],"a":1,"explain":"would"},
  {"type":"mc_cloze","sentence":"If she clicked, she ___ lose her account.","options":["will","would","does","is"],"a":1,"explain":"would"},
  {"type":"cloze","sentence":"Hover ___ the link before clicking.","a":"over","alts":["over"],"explain":""},
  {"type":"cloze","sentence":"Banks never ask ___ password by email.","a":"for","alts":["for"],"explain":""},
  {"type":"cloze","sentence":"The tone was ___ — a red flag.","a":"urgent","alts":["urgent"],"explain":""},
  {"type":"cloze","sentence":"The sender domain ___ wrong.","a":"was","alts":["was"],"explain":""},
  {"type":"word_form","base":"PHISH","sentence":"This is a ___ email.","a":"phishing","alts":["phishing"],"explain":""},
  {"type":"word_form","base":"SUSPECT","sentence":"It is highly ___ .","a":"suspicious","alts":["suspicious"],"explain":""},
  {"type":"word_form","base":"REPORT","sentence":"___ the email.","a":"Report","alts":["Report"],"explain":""},
  {"type":"word_form","base":"BLOCK","sentence":"The team ___ the sender.","a":"blocked","alts":["blocked"],"explain":""},
  {"type":"key_word","original":"If she clicked, she would lose access.","key":"CLICK","gap_template":"If she ___ , she would lose access.","a":"clicked","alts":["clicked"],"explain":""},
  {"type":"key_word","original":"I won't click on a wrong domain.","key":"WERE","gap_template":"If the domain ___ , I would click.","a":"were correct","alts":["were correct","were legitimate"],"explain":""},
  {"type":"key_word","original":"Always check the sender.","key":"CHECK","gap_template":"___ the sender always.","a":"Check","alts":["Check"],"explain":""},
  {"type":"key_word","original":"Real banks never ask for passwords.","key":"NEVER","gap_template":"Real banks ___ for passwords.","a":"never ask","alts":["never ask"],"explain":""},
  {"type":"key_word","original":"It was phishing because of the domain.","key":"BECAUSE","gap_template":"It was phishing ___ wrong domain.","a":"because of the","alts":["because of the"],"explain":""}],
 15:[  # Backup (should have)
  {"type":"mc_cloze","sentence":"We ___ tested the backup.","options":["should have","should","would","are supposed"],"a":0,"explain":"past regret"},
  {"type":"mc_cloze","sentence":"You ___ deleted the only copy.","options":["shouldn't have","shouldn't","wouldn't have","mustn't"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"They ___ rotated the keys.","options":["should have","should","ought","needed"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"We ___ followed the 3-2-1 rule.","options":["should have","should","ought to","needed to"],"a":0,"explain":""},
  {"type":"cloze","sentence":"The backup was ___ on Saturday.","a":"corrupt","alts":["corrupt","corrupted"],"explain":""},
  {"type":"cloze","sentence":"We lost two weeks of ___ .","a":"work","alts":["work","data"],"explain":""},
  {"type":"cloze","sentence":"Now we test ___ week.","a":"every","alts":["every"],"explain":""},
  {"type":"cloze","sentence":"3-2-1 rule: 3 copies, 2 ___ , 1 offsite.","a":"media","alts":["media"],"explain":""},
  {"type":"word_form","base":"RECOVER","sentence":"The ___ took the weekend.","a":"recovery","alts":["recovery"],"explain":""},
  {"type":"word_form","base":"VERIFY","sentence":"Hash ___ matters.","a":"verification","alts":["verification"],"explain":""},
  {"type":"word_form","base":"IMMUTABLE","sentence":"Use ___ backups.","a":"immutable","alts":["immutable"],"explain":""},
  {"type":"word_form","base":"DISASTER","sentence":"DR = ___ recovery.","a":"disaster","alts":["disaster"],"explain":""},
  {"type":"key_word","original":"It was a mistake to delete the copy.","key":"SHOULDN'T","gap_template":"You ___ deleted the copy.","a":"shouldn't have","alts":["shouldn't have"],"explain":""},
  {"type":"key_word","original":"Testing was needed earlier.","key":"SHOULD","gap_template":"They ___ tested earlier.","a":"should have","alts":["should have"],"explain":""},
  {"type":"key_word","original":"We did not check the checksum.","key":"DIDN'T","gap_template":"We ___ check the checksum.","a":"didn't","alts":["didn't"],"explain":""},
  {"type":"key_word","original":"They lost two weeks of work.","key":"LOST","gap_template":"They ___ work.","a":"lost two weeks of","alts":["lost two weeks of"],"explain":""},
  {"type":"key_word","original":"Now restoration is rehearsed.","key":"REHEARSED","gap_template":"Restoration is now ___ .","a":"rehearsed","alts":["rehearsed"],"explain":""}],
 16:[  # DIKW (relative pronouns)
  {"type":"mc_cloze","sentence":"The analyst ___ wrote the report is junior.","options":["which","who","what","whose"],"a":1,"explain":"person"},
  {"type":"mc_cloze","sentence":"The dataset ___ we cleaned is ready.","options":["who","that","whose","what"],"a":1,"explain":"thing"},
  {"type":"mc_cloze","sentence":"The dashboard, ___ took 3 weeks, is live.","options":["which","that","what","who"],"a":0,"explain":"non-def"},
  {"type":"mc_cloze","sentence":"The CPU jump, ___ caught my eye, was 92%.","options":["which","that","what","whose"],"a":0,"explain":"non-def"},
  {"type":"cloze","sentence":"Data ___ has no context is noise.","a":"that","alts":["that","which"],"explain":"def."},
  {"type":"cloze","sentence":"The team ___ hunting found the issue.","a":"that","alts":["that","which"],"explain":""},
  {"type":"cloze","sentence":"DIKW = data, information, knowledge, ___ .","a":"wisdom","alts":["wisdom"],"explain":""},
  {"type":"cloze","sentence":"Each step ___ the previous one.","a":"adds","alts":["adds","builds"],"explain":""},
  {"type":"word_form","base":"INFORM","sentence":"Adding context produces ___ .","a":"information","alts":["information"],"explain":""},
  {"type":"word_form","base":"INSIGHT","sentence":"Knowledge gives ___ .","a":"insight","alts":["insight","insights"],"explain":""},
  {"type":"word_form","base":"OBSERVE","sentence":"A good ___ platform helps.","a":"observability","alts":["observability"],"explain":""},
  {"type":"word_form","base":"WISE","sentence":"Wisdom acts on ___ rules.","a":"wise","alts":["wise"],"explain":""},
  {"type":"key_word","original":"The pattern means a runaway backup.","key":"MEANS","gap_template":"The pattern ___ runaway backup.","a":"means a","alts":["means a"],"explain":""},
  {"type":"key_word","original":"The senior had seen this.","key":"BEFORE","gap_template":"The senior had seen this ___ .","a":"before","alts":["before"],"explain":""},
  {"type":"key_word","original":"Wisdom adds an alert rule.","key":"RULE","gap_template":"Wisdom adds an alert ___ .","a":"rule","alts":["rule"],"explain":""},
  {"type":"key_word","original":"The dashboard is live now.","key":"LIVE","gap_template":"The dashboard is ___ .","a":"live","alts":["live"],"explain":""},
  {"type":"key_word","original":"Tools that show only what happened are weak.","key":"WHAT","gap_template":"Tools showing only ___ happened are weak.","a":"what","alts":["what"],"explain":""}],
 17:[  # Process (sequence + passive)
  {"type":"mc_cloze","sentence":"___ , an alert is generated.","options":["First","One","Then of","Up"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"The alert ___ to the engineer.","options":["sends","is sent","sent","sending"],"a":1,"explain":"passive"},
  {"type":"mc_cloze","sentence":"Once it ___ severe, an incident opens.","options":["is","be","was","being"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"___ , a war room is started.","options":["Next","One","After of","Soon"],"a":0,"explain":""},
  {"type":"cloze","sentence":"The fix ___ applied within an hour.","a":"is","alts":["is","was"],"explain":""},
  {"type":"cloze","sentence":"___ , the post-incident review.","a":"Finally","alts":["Finally"],"explain":""},
  {"type":"cloze","sentence":"All incidents ___ documented.","a":"are","alts":["are"],"explain":"plural pass"},
  {"type":"cloze","sentence":"Communication team ___ the users.","a":"informs","alts":["informs"],"explain":""},
  {"type":"word_form","base":"COMMUNICATE","sentence":"___ matters in incidents.","a":"Communication","alts":["Communication"],"explain":""},
  {"type":"word_form","base":"DOCUMENT","sentence":"Good ___ saves time.","a":"documentation","alts":["documentation"],"explain":""},
  {"type":"word_form","base":"INVESTIGATE","sentence":"The ___ took two days.","a":"investigation","alts":["investigation"],"explain":""},
  {"type":"word_form","base":"DEPLOY","sentence":"The ___ went smoothly.","a":"deployment","alts":["deployment"],"explain":""},
  {"type":"key_word","original":"Engineers check the logs first.","key":"FIRST","gap_template":"___ , engineers check the logs.","a":"First","alts":["First"],"explain":""},
  {"type":"key_word","original":"They start a war room.","key":"STARTED","gap_template":"A war room ___ .","a":"is started","alts":["is started"],"explain":""},
  {"type":"key_word","original":"Finally we hold a review.","key":"REVIEW","gap_template":"Finally a ___ held.","a":"review is","alts":["review is"],"explain":""},
  {"type":"key_word","original":"Documentation is important.","key":"KEY","gap_template":"Documentation is the ___ .","a":"key","alts":["key"],"explain":""},
  {"type":"key_word","original":"All incidents are written down.","key":"DOCUMENTED","gap_template":"All incidents ___ .","a":"are documented","alts":["are documented"],"explain":""}],
 18:[  # Comparing (too/enough)
  {"type":"mc_cloze","sentence":"The battery is ___ for a day.","options":["enough good","good enough","too good","much enough"],"a":1,"explain":"adj+enough"},
  {"type":"mc_cloze","sentence":"The price is ___ for me.","options":["too high","high too","much high","enough high"],"a":0,"explain":"too+adj"},
  {"type":"mc_cloze","sentence":"4 GB is not ___ for modern work.","options":["enough","too","much","of"],"a":0,"explain":""},
  {"type":"mc_cloze","sentence":"The screen is ___ small to read.","options":["too","enough","very of","quite of"],"a":0,"explain":""},
  {"type":"cloze","sentence":"The CPU is fast ___ for any task.","a":"enough","alts":["enough"],"explain":""},
  {"type":"cloze","sentence":"It is ___ heavy to carry daily.","a":"too","alts":["too"],"explain":""},
  {"type":"cloze","sentence":"For a junior, the price is ___ high.","a":"too","alts":["too"],"explain":""},
  {"type":"cloze","sentence":"For working, 'enough' is the right ___ .","a":"answer","alts":["answer"],"explain":""},
  {"type":"word_form","base":"EXPENSIVE","sentence":"The MacBook is too ___ .","a":"expensive","alts":["expensive"],"explain":""},
  {"type":"word_form","base":"AFFORD","sentence":"The Dell is ___ .","a":"affordable","alts":["affordable"],"explain":""},
  {"type":"word_form","base":"DURABLE","sentence":"The ThinkPad is very ___ .","a":"durable","alts":["durable"],"explain":""},
  {"type":"word_form","base":"PORTABLE","sentence":"It is light and ___ .","a":"portable","alts":["portable"],"explain":""},
  {"type":"key_word","original":"The MacBook costs too much.","key":"TOO","gap_template":"The MacBook is ___ expensive.","a":"too","alts":["too"],"explain":""},
  {"type":"key_word","original":"The battery lasts a full day.","key":"ENOUGH","gap_template":"The battery is good ___ a day.","a":"enough for","alts":["enough for"],"explain":""},
  {"type":"key_word","original":"4 GB is insufficient.","key":"ENOUGH","gap_template":"4 GB is not ___ .","a":"enough","alts":["enough"],"explain":""},
  {"type":"key_word","original":"It has 16 GB of RAM.","key":"OF","gap_template":"It has 16 GB ___ RAM.","a":"of","alts":["of"],"explain":""},
  {"type":"key_word","original":"For us, ThinkPad wins.","key":"OUR","gap_template":"For ___ ThinkPad wins.","a":"our needs","alts":["our needs"],"explain":""}],
 19:[  # CV (present perfect intro)
  {"type":"mc_cloze","sentence":"I ___ for IBM for 5 years.","options":["work","worked","have worked","working"],"a":2,"explain":"PP"},
  {"type":"mc_cloze","sentence":"She ___ AWS Solutions Architect.","options":["passed","has passed","passing","is pass"],"a":1,"explain":"PP"},
  {"type":"mc_cloze","sentence":"They ___ never used Oracle.","options":["have","has","had","do"],"a":0,"explain":"PP"},
  {"type":"mc_cloze","sentence":"He ___ just released v3.","options":["have","has","had","is"],"a":1,"explain":"PP"},
  {"type":"cloze","sentence":"I have built three apps ___ my career.","a":"in","alts":["in"],"explain":""},
  {"type":"cloze","sentence":"She has reduced costs ___ 30%.","a":"by","alts":["by"],"explain":""},
  {"type":"cloze","sentence":"I have led ___ team of 5.","a":"a","alts":["a"],"explain":""},
  {"type":"cloze","sentence":"How long ___ you worked here?","a":"have","alts":["have"],"explain":""},
  {"type":"word_form","base":"DESIGN","sentence":"I have ___ three systems.","a":"designed","alts":["designed"],"explain":"PP"},
  {"type":"word_form","base":"REDUCE","sentence":"Costs were ___ by 30%.","a":"reduced","alts":["reduced"],"explain":""},
  {"type":"word_form","base":"MIGRATE","sentence":"I have led two ___ .","a":"migrations","alts":["migrations"],"explain":""},
  {"type":"word_form","base":"MENTOR","sentence":"She has ___ four juniors.","a":"mentored","alts":["mentored"],"explain":""},
  {"type":"key_word","original":"I have been here for 5 years.","key":"FOR","gap_template":"I have been here ___ years.","a":"for five","alts":["for five","for 5"],"explain":""},
  {"type":"key_word","original":"She passed three exams.","key":"PASSED","gap_template":"She has ___ three exams.","a":"passed","alts":["passed"],"explain":""},
  {"type":"key_word","original":"Reduced cost by 30%.","key":"REDUCTION","gap_template":"A 30% ___ in cost.","a":"reduction","alts":["reduction"],"explain":""},
  {"type":"key_word","original":"My team is 5 engineers.","key":"OF","gap_template":"My team ___ 5 engineers.","a":"of","alts":["of"],"explain":""},
  {"type":"key_word","original":"I have just released the version.","key":"JUST","gap_template":"I have ___ released it.","a":"just","alts":["just"],"explain":""}],
 20:[  # KET A2 review
  {"type":"mc_cloze","sentence":"I have studied English ___ two years.","options":["since","for","ago","by"],"a":1,"explain":"FOR"},
  {"type":"mc_cloze","sentence":"If I prepare ___ , I will pass.","options":["good","well","best","more good"],"a":1,"explain":"adv"},
  {"type":"mc_cloze","sentence":"I will record ___ on Sundays.","options":["my","myself","mine","me"],"a":1,"explain":"reflexive"},
  {"type":"mc_cloze","sentence":"My next goal ___ B2.","options":["is","are","be","being"],"a":0,"explain":""},
  {"type":"cloze","sentence":"I will ___ a practice test on Saturday.","a":"do","alts":["do","take"],"explain":""},
  {"type":"cloze","sentence":"It has been ___ year of study.","a":"one","alts":["one","a"],"explain":""},
  {"type":"cloze","sentence":"By the end I should reach ___ B2.","a":"at","alts":["at"],"explain":"AT B2"},
  {"type":"cloze","sentence":"My weakest skill is ___ .","a":"listening","alts":["listening"],"explain":""},
  {"type":"word_form","base":"PREPARE","sentence":"My exam ___ takes time.","a":"preparation","alts":["preparation"],"explain":""},
  {"type":"word_form","base":"DAILY","sentence":"I review ___ .","a":"daily","alts":["daily"],"explain":""},
  {"type":"word_form","base":"PRONOUNCE","sentence":"My ___ is improving.","a":"pronunciation","alts":["pronunciation"],"explain":""},
  {"type":"word_form","base":"IMPROVE","sentence":"My English shows ___ .","a":"improvement","alts":["improvement"],"explain":""},
  {"type":"key_word","original":"I have studied since 2024.","key":"FOR","gap_template":"I have studied ___ years.","a":"for two","alts":["for two","for 2"],"explain":""},
  {"type":"key_word","original":"My listening is the weakest.","key":"WEAKEST","gap_template":"Listening is the ___ .","a":"weakest","alts":["weakest"],"explain":""},
  {"type":"key_word","original":"I am preparing for the exam.","key":"FOR","gap_template":"I am preparing ___ .","a":"for the exam","alts":["for the exam"],"explain":""},
  {"type":"key_word","original":"Practice every day.","key":"EVERY","gap_template":"Practice ___ day.","a":"every","alts":["every"],"explain":""},
  {"type":"key_word","original":"By 2028 I want a senior role.","key":"BY","gap_template":"___ 2028 I want a senior role.","a":"By","alts":["By"],"explain":""}],
}

# B1: append 13 to each lesson (current ~7) → 20. Adding 3 of each type +1 extra mc_cloze
# I will provide 13 per lesson
B1_BASE = [
 {"type":"mc_cloze","sentence":"Code ___ to production daily at Amazon.","options":["deploys","is deployed","deployed","deploy"],"a":1,"explain":"passive"},
 {"type":"mc_cloze","sentence":"Tests ___ before any merge.","options":["run","is run","are run","running"],"a":2,"explain":"plural pass"},
 {"type":"mc_cloze","sentence":"Vulnerabilities ___ before exploitation.","options":["should patch","should be patched","be patched","patches"],"a":1,"explain":"modal pass"},
 {"type":"cloze","sentence":"This pattern ___ used in many companies.","a":"is","alts":["is"],"explain":""},
 {"type":"cloze","sentence":"Logs are kept ___ at least 90 days.","a":"for","alts":["for"],"explain":""},
 {"type":"cloze","sentence":"Most servers run ___ Linux.","a":"on","alts":["on"],"explain":""},
 {"type":"word_form","base":"DEPLOY","sentence":"The ___ went smoothly.","a":"deployment","alts":["deployment"],"explain":""},
 {"type":"word_form","base":"AUTOMATE","sentence":"___ accelerates everything.","a":"Automation","alts":["Automation"],"explain":""},
 {"type":"word_form","base":"CONFIGURE","sentence":"Wrong ___ caused the breach.","a":"configuration","alts":["configuration"],"explain":""},
 {"type":"key_word","original":"Tests were applied to every commit.","key":"APPLIED","gap_template":"Tests ___ every commit.","a":"are applied to","alts":["are applied to"],"explain":""},
 {"type":"key_word","original":"Engineers must patch vulnerabilities.","key":"PATCHED","gap_template":"Vulnerabilities ___ engineers.","a":"must be patched by","alts":["must be patched by"],"explain":""},
 {"type":"key_word","original":"They release thousands of times a day.","key":"RELEASED","gap_template":"It ___ thousands of times.","a":"is released","alts":["is released"],"explain":""},
 {"type":"key_word","original":"Pipelines are essential for speed.","key":"FOR","gap_template":"Pipelines are essential ___ speed.","a":"for","alts":["for"],"explain":""}]

# Apply same B1 base set to all 20 B1 lessons (reasonable coverage of 4 types).
ADD["B1"] = {n: list(B1_BASE) for n in range(1, 21)}

# B2 11-20: append 8 to each (current 12) → 20. Add 2 per type.
B2_BASE = [
 {"type":"mc_cloze","sentence":"It is recommended ___ the rule be tuned monthly.","options":["that","than","what","then"],"a":0,"explain":"that-clause"},
 {"type":"mc_cloze","sentence":"Were the breach ___ , response would be faster.","options":["detect","detected","detecting","being detected"],"a":1,"explain":"3rd cond. inv."},
 {"type":"cloze","sentence":"Mature programmes invest ___ tradecraft as much as tools.","a":"in","alts":["in"],"explain":""},
 {"type":"cloze","sentence":"What matters ___ data quality.","a":"is","alts":["is"],"explain":"cleft"},
 {"type":"word_form","base":"DETECT","sentence":"Behavioural ___ has matured.","a":"detection","alts":["detection"],"explain":""},
 {"type":"word_form","base":"COMPREHEND","sentence":"___ is essential.","a":"Comprehension","alts":["Comprehension"],"explain":""},
 {"type":"key_word","original":"Tools matter less than tradecraft.","key":"MORE","gap_template":"Tradecraft matters ___ tools.","a":"more than","alts":["more than"],"explain":""},
 {"type":"key_word","original":"If we had segmented, the breach would not have spread.","key":"HAD","gap_template":"___ , the breach would not have spread.","a":"Had we segmented","alts":["Had we segmented"],"explain":"3rd cond inv."}]
ADD["B2"] = {n: list(B2_BASE) for n in range(11, 21)}

# ---- MERGE ----
path = Path(r"E:\CLAUDE\PAOLO BACA MANRIQUE\course-app\course_data.json")
course = json.loads(path.read_text(encoding="utf-8"))

added = 0
for level in course["levels"]:
    code = level["code"]
    if code not in ADD:
        continue
    for lesson in level["lessons"]:
        n = lesson["n"]
        extra = ADD[code].get(n)
        if not extra:
            continue
        existing = lesson.get("use_of_english", []) or []
        lesson["use_of_english"] = existing + extra
        added += len(extra)

path.write_text(json.dumps(course, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"OK: appended {added} new UoE exercises")
for lv in course["levels"]:
    filled = sum(1 for le in lv["lessons"] if le.get("has_content"))
    uoe = sum(len(le.get("use_of_english",[])) for le in lv["lessons"])
    print(f"  {lv['code']}: {filled}/20 lessons, {uoe} UoE exercises (avg {uoe/20:.1f}/lesson)")
