# -*- coding: utf-8 -*-
"""
Use of English exercises for the 30 pilot lessons.
Types per level:
 A1  \u2192 mc_cloze + cloze + word_form (simple)
 A2  \u2192 mc_cloze + cloze + word_form
 B1  \u2192 mc_cloze + cloze + word_form + key_word (intro)
 B2  \u2192 FCE-style 4 parts
 C1  \u2192 CAE-style 4 parts (harder distractors)
 C2  \u2192 CPE-style 4 parts (idioms, register)
"""
import json
from pathlib import Path

UOE = {
"A1": {
 1: [ # Hello, I'm a systems engineer  (Verb BE, subject pronouns, a/an)
  {"type":"mc_cloze","sentence":"Juan ___ a systems engineer.",
   "options":["am","is","are","be"],"a":1,
   "explain":"Third person singular \u2192 IS."},
  {"type":"mc_cloze","sentence":"I ___ from Peru.",
   "options":["am","is","are","be"],"a":0,
   "explain":"First person singular \u2192 AM."},
  {"type":"cloze","sentence":"I am ___ engineer. I work at a tech company.",
   "a":"an","alts":["an"],
   "explain":"AN before a vowel sound (engineer starts with /e/)."},
  {"type":"word_form","base":"ENGINE","sentence":"Juan is a systems ___ .",
   "a":"engineer","alts":["engineer"],
   "explain":"Noun for the profession: engine + -eer."},
 ],
 2: [ # The alphabet of URLs and emails
  {"type":"mc_cloze","sentence":"We say '___' for the @ symbol.",
   "options":["dot","at","slash","hash"],"a":1,"explain":"'@' = at."},
  {"type":"cloze","sentence":"The URL https://nist.gov uses a ___ before 'gov'.",
   "a":"dot","alts":["dot",".","period"],
   "explain":"The '.' is spelled 'dot' in URLs."},
  {"type":"mc_cloze","sentence":"B in the NATO alphabet is ___ .",
   "options":["Boy","Bravo","Ball","Bear"],"a":1,"explain":"NATO B = Bravo."},
 ],
 3: [ # Numbers, versions and dates
  {"type":"mc_cloze","sentence":"Python 3.12.4 \u2014 the '12' is the ___ number.",
   "options":["major","minor","patch","final"],"a":1,"explain":"major.MINOR.patch."},
  {"type":"cloze","sentence":"Patch Tuesday is the second ___ of the month.",
   "a":"Tuesday","alts":["tuesday","Tuesday"],"explain":"Second Tuesday each month."},
  {"type":"word_form","base":"UPDATE",
   "sentence":"Engineers check for ___ every week.",
   "a":"updates","alts":["updates"],
   "explain":"Plural noun; regular verb -> noun (adding -s)."},
 ],
 4: [ # Hardware parts
  {"type":"mc_cloze","sentence":"The ___ is the brain of the computer.",
   "options":["RAM","CPU","SSD","USB"],"a":1,"explain":"CPU = Central Processing Unit."},
  {"type":"cloze","sentence":"There ___ many parts inside a computer.",
   "a":"are","alts":["are"],"explain":"Plural subject 'parts' \u2192 there ARE."},
  {"type":"word_form","base":"PROCESS",
   "sentence":"The CPU is the ___ of the computer.",
   "a":"processor","alts":["processor"],
   "explain":"Agent noun: process + -or \u2192 processor."},
 ],
 5: [ # Software basics
  {"type":"mc_cloze","sentence":"___ to download software from strange sites.",
   "options":["Do","Don't","Can","Should"],"a":1,"explain":"Negative imperative: Don't."},
  {"type":"cloze","sentence":"Linux is ___ . Anyone can read the code.",
   "a":"free","alts":["free"],"explain":"Adjective: free (no cost)."},
  {"type":"word_form","base":"INSTALL",
   "sentence":"The ___ asks for your password.",
   "a":"installer","alts":["installer"],
   "explain":"Agent noun: install + -er \u2192 installer."},
 ],
},
"A2": {
 1: [ # Describing IT jobs (Present simple vs continuous)
  {"type":"mc_cloze","sentence":"A software developer ___ code every day.",
   "options":["write","writes","is writing","written"],"a":1,
   "explain":"Third person singular present simple \u2192 writes."},
  {"type":"mc_cloze","sentence":"Look! The SOC analyst ___ an alert right now.",
   "options":["investigates","is investigating","investigate","has investigated"],"a":1,
   "explain":"Present continuous for action happening now."},
  {"type":"cloze","sentence":"A lead engineer guides the team and ___ decisions.",
   "a":"makes","alts":["makes"],"explain":"Parallel structure; make decisions."},
  {"type":"word_form","base":"RESPONSIBLE",
   "sentence":"The engineer has a lot of ___ in this project.",
   "a":"responsibility","alts":["responsibility"],
   "explain":"Adjective \u2192 noun: responsible \u2192 responsibility."},
 ],
 2: [ # Past simple (work history)
  {"type":"mc_cloze","sentence":"Maria ___ her career in 2019.",
   "options":["start","starts","started","starting"],"a":2,
   "explain":"Past simple regular: start \u2192 started."},
  {"type":"mc_cloze","sentence":"Last year, she ___ to a cloud company.",
   "options":["moved","moves","is moving","has moved"],"a":0,
   "explain":"Past simple with 'last year' (specific past time)."},
  {"type":"cloze","sentence":"She ___ not have experience with AWS before 2022.",
   "a":"did","alts":["did"],"explain":"Past simple negative: did + not."},
  {"type":"word_form","base":"CERTIFY",
   "sentence":"Last year she got a ___ in cybersecurity.",
   "a":"certificate","alts":["certificate","certification"],
   "explain":"Verb \u2192 noun: certify \u2192 certificate."},
 ],
 3: [ # Operating systems (comparatives)
  {"type":"mc_cloze","sentence":"Linux is ___ popular OS for cloud servers in the world.",
   "options":["the most","more","most","the more"],"a":0,
   "explain":"Superlative of multi-syllable adj: the most popular."},
  {"type":"mc_cloze","sentence":"macOS is ___ than Linux for graphic design, many people think.",
   "options":["good","gooder","better","the best"],"a":2,
   "explain":"Irregular comparative: good \u2192 better."},
  {"type":"cloze","sentence":"Windows is ___ user-friendly ___ Linux for beginners.",
   "a":"more than","alts":["more than"],
   "explain":"More + adjective + than (comparative of long adjectives)."},
  {"type":"word_form","base":"FLEXIBLE",
   "sentence":"Linux is famous for its ___ .",
   "a":"flexibility","alts":["flexibility"],"explain":"Adj \u2192 noun: -ity."},
 ],
 4: [ # Installing software (sequence)
  {"type":"mc_cloze","sentence":"First, go to the official website. ___, download the installer.",
   "options":["Then","After","Later","Finally"],"a":0,"explain":"Sequence: First \u2192 Then."},
  {"type":"cloze","sentence":"You may need administrator rights, ___ the system will ask for your password.",
   "a":"so","alts":["so"],"explain":"Result connector: so."},
  {"type":"word_form","base":"VERIFY",
   "sentence":"Good projects publish a hash for ___ .",
   "a":"verification","alts":["verification"],
   "explain":"Verb \u2192 noun: verify \u2192 verification."},
 ],
 5: [ # Web browsers (modal advice: should)
  {"type":"mc_cloze","sentence":"You ___ install extensions only from the official store.",
   "options":["must not","should","can","needn't"],"a":1,
   "explain":"Strong recommendation: should."},
  {"type":"mc_cloze","sentence":"Chrome ___ the biggest market share today.",
   "options":["have","has","is having","had"],"a":1,
   "explain":"Present simple, third person singular: has."},
  {"type":"cloze","sentence":"For real privacy, you should ___ a VPN or Tor.",
   "a":"use","alts":["use"],"explain":"Modal + bare infinitive."},
  {"type":"word_form","base":"PRIVATE",
   "sentence":"Firefox is famous for its strong ___ features.",
   "a":"privacy","alts":["privacy"],"explain":"Adj \u2192 noun: private \u2192 privacy."},
 ],
},
"B1": {
 1: [ # SDLC
  {"type":"mc_cloze","sentence":"Every time a developer pushes new code, automated pipelines ___ it.",
   "options":["test","tests","are testing","would test"],"a":0,
   "explain":"Subject 'pipelines' is plural \u2192 test."},
  {"type":"cloze","sentence":"Waterfall has been largely replaced ___ agile approaches in the last two decades.",
   "a":"by","alts":["by"],"explain":"Passive voice + agent: replaced BY."},
  {"type":"word_form","base":"DEVELOP",
   "sentence":"The ___ writes code during the implementation phase.",
   "a":"developer","alts":["developer"],"explain":"Agent noun: develop \u2192 developer."},
  {"type":"key_word","original":"Amazon deploys code to production thousands of times every day.",
   "key":"DEPLOYED","gap_template":"Code ___ to production thousands of times every day at Amazon.",
   "a":"is deployed","alts":["is deployed"],
   "explain":"Active \u2192 passive: 'is deployed' (present simple passive)."},
 ],
 2: [ # Programming languages
  {"type":"mc_cloze","sentence":"Rust is famous for ___ memory-safe without a garbage collector.",
   "options":["be","being","been","to being"],"a":1,
   "explain":"Preposition 'for' + gerund: being."},
  {"type":"mc_cloze","sentence":"Kubernetes ___ in Go, so every system engineer meets Go sooner or later.",
   "options":["writes","is written","has written","writing"],"a":1,
   "explain":"Passive: 'is written' (things don't write themselves)."},
  {"type":"cloze","sentence":"CISA has encouraged companies to ___ critical software to memory-safe languages.",
   "a":"migrate","alts":["migrate"],"explain":"Collocation: migrate software."},
  {"type":"key_word","original":"Python has a cleaner syntax than most other languages.",
   "key":"THAN","gap_template":"Most other languages have ___ Python.",
   "a":"a less clean syntax than","alts":["a less clean syntax than","less clean syntax than"],
   "explain":"Comparative reversal."},
 ],
 3: [ # Databases
  {"type":"mc_cloze","sentence":"NoSQL appeared around 2009, ___ needed to handle enormous volumes of data.",
   "options":["when companies","companies","that companies","which companies"],"a":0,
   "explain":"Time clause with 'when' + subject 'companies'."},
  {"type":"cloze","sentence":"MongoDB stores data ___ flexible JSON objects.",
   "a":"as","alts":["as"],"explain":"'Store as' + format."},
  {"type":"word_form","base":"CONSISTENT",
   "sentence":"Bank transactions must be 100% ___ .",
   "a":"consistent","alts":["consistent"],"explain":"Adjective: no change (already adjective)."},
  {"type":"key_word","original":"The team uses parameterised queries to prevent SQL injection.",
   "key":"ORDER","gap_template":"The team uses parameterised queries in ___ prevent SQL injection.",
   "a":"order to","alts":["order to"],"explain":"Purpose clause: 'in order to'."},
 ],
 4: [ # Cloud IaaS/PaaS/SaaS
  {"type":"mc_cloze","sentence":"If your data is flexible and changes often, NoSQL ___ usually better.",
   "options":["is","will be","would be","has been"],"a":0,
   "explain":"Real/general conditional: present simple in result clause."},
  {"type":"cloze","sentence":"The provider is responsible ___ the security of the cloud.",
   "a":"for","alts":["for"],"explain":"Collocation: responsible FOR."},
  {"type":"word_form","base":"RESPONSIBLE",
   "sentence":"Customers keep ___ for their data configuration.",
   "a":"responsibility","alts":["responsibility"],"explain":"Adj \u2192 noun: -ility."},
  {"type":"key_word","original":"Capital One was hacked because a WAF was misconfigured.",
   "key":"DUE","gap_template":"Capital One was hacked ___ a misconfigured WAF.",
   "a":"due to","alts":["due to"],"explain":"Cause: 'due to' + noun phrase."},
 ],
 5: [ # Networks
  {"type":"mc_cloze","sentence":"TCP performs a handshake ___ any data is sent.",
   "options":["before","after","during","while"],"a":0,
   "explain":"Sequence of events: handshake first, then data."},
  {"type":"cloze","sentence":"UDP does not do any handshake \u2014 it simply sends packets and ___ for the best.",
   "a":"hopes","alts":["hopes"],"explain":"Idiom: 'hope for the best'. Third person singular."},
  {"type":"word_form","base":"FRAGMENT",
   "sentence":"IP ___ attacks exploit how packets are split.",
   "a":"fragmentation","alts":["fragmentation"],"explain":"-ation noun."},
  {"type":"key_word","original":"A SYN flood targets the transport layer.",
   "key":"AIMED","gap_template":"A SYN flood ___ the transport layer.",
   "a":"is aimed at","alts":["is aimed at"],"explain":"Passive with 'aim at'."},
 ],
},
"B2": {
 1: [ # Incident response (NIST 800-61)
  {"type":"mc_cloze","sentence":"Organisations ___ underestimate the Preparation phase.",
   "options":["often","hardly","rarely ever","scarcely"],"a":0,
   "explain":"'Often' fits naturally; the others contradict the passage."},
  {"type":"cloze","sentence":"A mature programme also includes retainer agreements ___ external forensic firms.",
   "a":"with","alts":["with"],"explain":"Collocation: agreement WITH."},
  {"type":"word_form","base":"CONTAIN",
   "sentence":"Short-term ___ means isolating the affected host immediately.",
   "a":"containment","alts":["containment"],"explain":"-ment noun."},
  {"type":"key_word","original":"If you skip the Preparation phase, you will probably pay for it later.",
   "key":"SKIPPED","gap_template":"The Preparation phase ___ without serious later consequences.",
   "a":"cannot be skipped","alts":["cannot be skipped","can't be skipped"],
   "explain":"Modal passive: cannot be + past participle."},
 ],
 2: [ # Network security architecture
  {"type":"mc_cloze","sentence":"___ 95% of enterprise traffic is encrypted, blind spots have grown.",
   "options":["Although","Because","However","Despite"],"a":1,
   "explain":"Cause clause \u2192 Because."},
  {"type":"cloze","sentence":"TLS inspection must be balanced ___ employee rights and regulatory constraints.",
   "a":"against","alts":["against"],"explain":"'Balance against'."},
  {"type":"word_form","base":"SEGMENT",
   "sentence":"Micro-___ goes further than traditional VLAN segmentation.",
   "a":"segmentation","alts":["segmentation"],"explain":"-ation noun."},
  {"type":"key_word","original":"A WAF protects web applications from injection attacks.",
   "key":"PROTECTED","gap_template":"Web applications ___ injection attacks by a WAF.",
   "a":"are protected from","alts":["are protected from"],
   "explain":"Active \u2192 passive + preposition 'from'."},
 ],
 3: [ # Ransomware
  {"type":"mc_cloze","sentence":"Almost every major operator ___ to double extortion since 2019.",
   "options":["has moved","moved","is moving","moves"],"a":0,
   "explain":"Present perfect with 'since 2019' (started in past, continues)."},
  {"type":"cloze","sentence":"Tested backups are the single most important control: attackers lose most ___ their leverage.",
   "a":"of","alts":["of"],"explain":"'Most of' + possessive."},
  {"type":"word_form","base":"EXTORT",
   "sentence":"In triple ___ , attackers add DDoS or contact customers.",
   "a":"extortion","alts":["extortion"],"explain":"Verb \u2192 noun: -ion."},
  {"type":"key_word","original":"Colonial Pipeline paid the ransom because it was afraid of lateral movement into OT.",
   "key":"FEAR","gap_template":"Colonial Pipeline paid the ransom ___ of lateral movement into OT.",
   "a":"for fear","alts":["for fear","out of fear"],"explain":"Idiomatic: 'for fear of'."},
 ],
 4: [ # Zero-day
  {"type":"mc_cloze","sentence":"___ a zero-day breaks the news, mature organisations already know their exposure.",
   "options":["By the time","Until","As soon as","Before"],"a":0,
   "explain":"'By the time X, Y has already happened'."},
  {"type":"cloze","sentence":"The EPSS score helps defenders ___ prioritise vulnerabilities.",
   "a":"to","alts":["to"],"explain":"'Help (sb) to + infinitive'."},
  {"type":"word_form","base":"EXPLOIT",
   "sentence":"The most dangerous category is remote code execution with public ___ in the wild.",
   "a":"exploitation","alts":["exploitation","exploits"],"explain":"Noun form."},
  {"type":"key_word","original":"A zero-day cannot be patched before it is publicly disclosed.",
   "key":"IMPOSSIBLE","gap_template":"It is ___ a zero-day before public disclosure.",
   "a":"impossible to patch","alts":["impossible to patch"],
   "explain":"'It is impossible to + infinitive'."},
 ],
 5: [ # OWASP Top 10
  {"type":"mc_cloze","sentence":"Injection ___ at the top of the list for more than a decade.",
   "options":["has been","was","is","had been"],"a":0,
   "explain":"Present perfect for state from past to recent time."},
  {"type":"cloze","sentence":"The root cause is almost always the same: concatenating untrusted input ___ using parameterised APIs.",
   "a":"instead of","alts":["instead of","rather than"],
   "explain":"Contrast phrase."},
  {"type":"word_form","base":"CONFIGURE",
   "sentence":"Security ___ remains in the OWASP Top 10.",
   "a":"misconfiguration","alts":["misconfiguration"],
   "explain":"Prefix 'mis-' + noun."},
  {"type":"key_word","original":"Insecure Design cannot be fixed by input sanitisation alone.",
   "key":"ENOUGH","gap_template":"Input sanitisation alone ___ Insecure Design.",
   "a":"is not enough to fix","alts":["is not enough to fix","isn't enough to fix"],
   "explain":"'Enough + to + infinitive' structure."},
 ],
},
"C1": {
 1: [ # CTI
  {"type":"mc_cloze","sentence":"Mature programmes ___ as much in tradecraft as they do in tools.",
   "options":["invest","are investing","invested","had invested"],"a":0,
   "explain":"General truth / habitual \u2192 present simple."},
  {"type":"cloze","sentence":"A team can drown ___ feeds while producing almost no real analysis.",
   "a":"in","alts":["in"],"explain":"'Drown in (data)'."},
  {"type":"word_form","base":"ATTRIBUTE",
   "sentence":"Pitfalls of ___ include cognitive bias and source dependence.",
   "a":"attribution","alts":["attribution"],"explain":"Verb \u2192 noun: -ion."},
  {"type":"key_word","original":"The Pyramid of Pain argues that TTPs should be prioritised over atomic indicators.",
   "key":"FAVOUR","gap_template":"The Pyramid of Pain argues ___ TTPs over atomic indicators.",
   "a":"in favour of","alts":["in favour of","in favor of"],
   "explain":"'Argue in favour of'."},
 ],
 2: [ # APTs
  {"type":"mc_cloze","sentence":"The blurring between espionage and destructive preparation is one of the ___ trends of recent years.",
   "options":["define","defining","defined","definer"],"a":1,
   "explain":"Present participle as adjective: 'defining trend'."},
  {"type":"cloze","sentence":"ICD 203 is widely adopted ___ commercial vendors such as Mandiant and CrowdStrike.",
   "a":"by","alts":["by"],"explain":"Passive + agent."},
  {"type":"word_form","base":"PERSIST",
   "sentence":"Kernel rootkits are a classic ___ mechanism.",
   "a":"persistence","alts":["persistence"],
   "explain":"Verb \u2192 noun: persist \u2192 persistence."},
  {"type":"key_word","original":"Signature-based approaches are no longer sufficient against modern APTs.",
   "key":"SUFFICE","gap_template":"Signature-based approaches ___ against modern APTs.",
   "a":"no longer suffice","alts":["no longer suffice"],
   "explain":"Lexical verb 'suffice' = 'be sufficient'."},
 ],
 3: [ # Zero Trust
  {"type":"mc_cloze","sentence":"No single vendor can ___ Zero Trust, despite what marketing suggests.",
   "options":["deliver","delivers","be delivering","have delivered"],"a":0,
   "explain":"Modal + base infinitive."},
  {"type":"cloze","sentence":"Pure Zero Trust is simply impractical ___ the device level in OT.",
   "a":"at","alts":["at"],"explain":"'At the X level' is the standard preposition."},
  {"type":"word_form","base":"VERIFY",
   "sentence":"Continuous ___ is a pillar of Zero Trust.",
   "a":"verification","alts":["verification"],"explain":"Verb \u2192 noun: -ation."},
  {"type":"key_word","original":"Zero Trust does not eliminate risk; it shifts it onto identity and instrumentation.",
   "key":"RATHER","gap_template":"___ risk, Zero Trust shifts it onto identity and instrumentation.",
   "a":"Rather than eliminating","alts":["Rather than eliminating"],
   "explain":"'Rather than + -ing' for preference."},
 ],
 4: [ # SOC
  {"type":"mc_cloze","sentence":"A SOC where analysts never see a successful detection they built themselves ___ its best people.",
   "options":["tends to lose","tends losing","tends lose","is tending lose"],"a":0,
   "explain":"'Tend + to + infinitive'."},
  {"type":"cloze","sentence":"Follow-the-sun models ___ multiple time zones alleviate some of the strain.",
   "a":"across","alts":["across"],"explain":"'Across time zones'."},
  {"type":"word_form","base":"MATURE",
   "sentence":"Coverage against MITRE ATT&CK measures a programme's ___ .",
   "a":"maturity","alts":["maturity"],"explain":"Adj \u2192 noun: -ity."},
  {"type":"key_word","original":"Only mature programmes really distinguish between collection and analysis.",
   "key":"MAKE","gap_template":"Only mature programmes really ___ between collection and analysis.",
   "a":"make a distinction","alts":["make a distinction","make the distinction"],
   "explain":"Lexical substitution: 'distinguish' \u2192 'make a distinction'."},
 ],
 5: [ # Threat hunting
  {"type":"mc_cloze","sentence":"A hunt that finds nothing ___ a failed hunt if the hypothesis was well framed.",
   "options":["is not","are not","has not been","was not"],"a":0,
   "explain":"Definitional present simple."},
  {"type":"cloze","sentence":"Programmes that treat null results as failure quickly devolve ___ theatre.",
   "a":"into","alts":["into"],"explain":"'Devolve INTO'."},
  {"type":"word_form","base":"HYPOTHESISE",
   "sentence":"Hunters build specific ___ about the adversary.",
   "a":"hypotheses","alts":["hypotheses"],
   "explain":"Irregular plural: hypothesis \u2192 hypotheses."},
  {"type":"key_word","original":"No query language can recover events that were never logged.",
   "key":"MATTER","gap_template":"It ___ query language you use if events were never logged.",
   "a":"does not matter what","alts":["does not matter what","doesn't matter what"],
   "explain":"Cleft with 'matter'."},
 ],
},
"C2": {
 1: [ # Grey zone
  {"type":"mc_cloze","sentence":"States, for entirely rational strategic reasons, ___ ambiguity.",
   "options":["prefer","are preferring","have preferred","had preferred"],"a":0,
   "explain":"General observation \u2192 present simple."},
  {"type":"cloze","sentence":"The legal architecture built around those categories may need to evolve faster ___ governments are institutionally prepared to evolve it.",
   "a":"than","alts":["than"],"explain":"Comparative 'faster than'."},
  {"type":"word_form","base":"LEGITIMATE",
   "sentence":"Private-sector attribution raises uncomfortable questions about ___ .",
   "a":"legitimacy","alts":["legitimacy"],"explain":"Adj \u2192 noun: -acy."},
  {"type":"key_word","original":"Observation and attack used to be clearly distinct categories.",
   "key":"WHAT","gap_template":"The clean analytical distinction ___ observation and attack is collapsing.",
   "a":"between","alts":["between"],"explain":"\u2014 note: drop 'WHAT' guidance; compare 'between'."},
 ],
 2: [ # State actors
  {"type":"mc_cloze","sentence":"Commercial spyware has been used ___ journalists, dissidents and parliamentarians.",
   "options":["against","before","over","from"],"a":0,
   "explain":"'Use against' someone."},
  {"type":"cloze","sentence":"Demand remains structural; supply, ___ turn, adapts.",
   "a":"in","alts":["in"],"explain":"'In turn' \u2192 sequence adverbial."},
  {"type":"word_form","base":"PROLIFERATE",
   "sentence":"The ___ of dual-use technology remains an open question.",
   "a":"proliferation","alts":["proliferation"],"explain":"-ation noun."},
  {"type":"key_word","original":"The 'one group, one state' model of the early APT era is increasingly obsolete.",
   "key":"HOLDS","gap_template":"The 'one group, one state' model of the early APT era increasingly ___ true.",
   "a":"no longer holds","alts":["no longer holds"],
   "explain":"Collocation: 'hold (true)' \u2192 idiomatic negation."},
 ],
 3: [ # Cyber law
  {"type":"mc_cloze","sentence":"Compliance is no longer a matter of choosing one framework and ___ to it.",
   "options":["adhere","adhering","adhered","to adhere"],"a":1,
   "explain":"Parallel structure after 'and' \u2192 gerund."},
  {"type":"cloze","sentence":"Navigating multiple, occasionally conflicting, obligations requires defensible records ___ the reasoning.",
   "a":"of","alts":["of"],"explain":"'Records of'."},
  {"type":"word_form","base":"SOVEREIGN",
   "sentence":"Data ___ concerns increasingly shape procurement decisions.",
   "a":"sovereignty","alts":["sovereignty"],
   "explain":"Adj \u2192 noun: sovereign \u2192 sovereignty."},
  {"type":"key_word","original":"The Court found that data subjects lacked effective judicial redress in the US.",
   "key":"ABSENCE","gap_template":"The Court found that there ___ effective judicial redress for data subjects in the US.",
   "a":"was an absence of","alts":["was an absence of"],
   "explain":"Nominalisation: 'lack' \u2192 'absence of'."},
 ],
 4: [ # Offensive ethics
  {"type":"mc_cloze","sentence":"What separates responsible research ___ criminal conduct is scope, consent, restraint and disclosure.",
   "options":["from","of","between","out"],"a":0,
   "explain":"'Separate X from Y'."},
  {"type":"cloze","sentence":"Extended embargoes can leave users exposed, sometimes ___ months on end.",
   "a":"for","alts":["for"],"explain":"Duration 'for + period'."},
  {"type":"word_form","base":"DISCLOSE",
   "sentence":"Coordinated vulnerability ___ is the dominant ethical framework.",
   "a":"disclosure","alts":["disclosure"],"explain":"Verb \u2192 noun: -ure."},
  {"type":"key_word","original":"The US DoJ said in 2022 that it would not prosecute good-faith security research.",
   "key":"ABJURED","gap_template":"In 2022, the US DoJ ___ of good-faith security research.",
   "a":"abjured prosecution","alts":["abjured prosecution","formally abjured prosecution"],
   "explain":"Formal register substitution of 'declined to prosecute'."},
 ],
 5: [ # Post-quantum crypto
  {"type":"mc_cloze","sentence":"Cryptography is embedded in virtually ___ layer of the computing stack.",
   "options":["every","all","each of","most of"],"a":0,
   "explain":"'Every + singular noun'."},
  {"type":"cloze","sentence":"A distressing share of enterprise software cannot accurately answer the apparently simple question ___ which algorithms it uses at runtime.",
   "a":"of","alts":["of"],"explain":"'Question OF'."},
  {"type":"word_form","base":"AGILE",
   "sentence":"Crypto-___ is no longer a nicety but an architectural requirement.",
   "a":"agility","alts":["agility"],"explain":"Adj \u2192 noun: -ility."},
  {"type":"key_word","original":"If a cryptographically relevant quantum computer arrives, today's encrypted traffic may be decrypted.",
   "key":"WERE","gap_template":"If a cryptographically relevant quantum computer ___ , today's encrypted traffic could be decrypted.",
   "a":"were to arrive","alts":["were to arrive"],
   "explain":"Formal second conditional: 'were to + infinitive'."},
 ],
},
}

# ---- merge ----
path = Path(r"E:\CLAUDE\PAOLO BACA MANRIQUE\course-app\course_data.json")
course = json.loads(path.read_text(encoding="utf-8"))

merged = 0; totals = {}
for level in course["levels"]:
    code = level["code"]
    totals[code] = 0
    for lesson in level["lessons"]:
        uoe = UOE.get(code, {}).get(lesson["n"])
        if uoe:
            lesson["use_of_english"] = uoe
            merged += 1
            totals[code] += len(uoe)
        else:
            lesson.setdefault("use_of_english", [])

path.write_text(json.dumps(course, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"OK: Merged Use of English into {merged} pilot lessons")
for code, n in totals.items():
    print(f"  {code}: {n} UoE exercises")
print(f"  Total: {sum(totals.values())} UoE exercises")
